import { NextRequest } from "next/server";
import { z } from "zod";

import {
  requireApiMember,
  createSupabaseForUser,
} from "@/app/api/v1/helpers/api-auth";
import { ok, err, dbErr, unauthorized } from "@/app/api/v1/helpers/response";
import { parseJson } from "@/app/api/v1/helpers/validate";

const schema = z.object({
  // `z.guid()`, not `z.uuid()`: zod 4's `uuid()` enforces the RFC 9562 version
  // and variant bits, and Postgres does not — any id that was not generated by
  // `gen_random_uuid()` (imported profiles, the seed users) is a valid `uuid`
  // column value that `uuid()` rejects. It made "new chat" fail outright.
  recipient_id: z.guid(),
});

export async function POST(request: NextRequest) {
  const ctx = await requireApiMember(request);
  if (!ctx) return unauthorized();

  const parsed = await parseJson(request, schema);
  if (!parsed.ok) return parsed.response;
  const { recipient_id } = parsed.data;

  if (recipient_id === ctx.userId) return err("Cannot create a thread with yourself");

  const supabase = createSupabaseForUser(request);

  /**
   * Who the caller may write to is decided by `messaging_contacts` — the same
   * security-definer RPC that fills the picker, so the two can never disagree.
   *
   * The previous check read `memberships` directly, under the caller's own
   * RLS: a parent cannot select another member's membership row, so every
   * recipient came back empty and *no parent or student could ever start a
   * chat* — a 403 on a contact the app had just offered them.
   */
  const { data: contacts, error: contactsError } = await supabase.rpc(
    "messaging_contacts",
    { p_mosque_id: ctx.mosqueId },
  );
  if (contactsError) return dbErr(contactsError.message);

  const allowed = (contacts ?? []).some(
    (c: { profile_id: string }) => c.profile_id === recipient_id,
  );
  if (!allowed) return err("Recipient not found in your mosque", 403);

  // Single query: find threads where I'm a participant AND recipient is a
  // participant AND total participant count == 2 (i.e. a real 1:1 chat).
  const { data: myParticipations } = await supabase
    .from("message_participants")
    .select("thread_id")
    .eq("profile_id", ctx.userId);

  const myThreadIds = (myParticipations ?? []).map((p) => p.thread_id);
  if (myThreadIds.length > 0) {
    const { data: candidates } = await supabase
      .from("message_participants")
      .select("thread_id, profile_id")
      .in("thread_id", myThreadIds);

    const byThread = new Map<string, Set<string>>();
    for (const row of candidates ?? []) {
      if (row.profile_id === null) continue;
      const set = byThread.get(row.thread_id) ?? new Set<string>();
      set.add(row.profile_id);
      byThread.set(row.thread_id, set);
    }
    for (const [threadId, participants] of byThread) {
      if (
        participants.size === 2 &&
        participants.has(ctx.userId) &&
        participants.has(recipient_id)
      ) {
        return ok({ threadId });
      }
    }
  }

  const { data: thread, error: tErr } = await supabase
    .from("message_threads")
    .insert({
      mosque_id: ctx.mosqueId,
      created_by: ctx.userId,
      updated_by: ctx.userId,
    })
    .select("id")
    .single();
  if (tErr || !thread) return dbErr(tErr?.message);

  const { error: pErr } = await supabase.from("message_participants").insert([
    {
      mosque_id: ctx.mosqueId,
      thread_id: thread.id,
      profile_id: ctx.userId,
      created_by: ctx.userId,
      updated_by: ctx.userId,
    },
    {
      mosque_id: ctx.mosqueId,
      thread_id: thread.id,
      profile_id: recipient_id,
      created_by: ctx.userId,
      updated_by: ctx.userId,
    },
  ]);
  if (pErr) return dbErr(pErr.message);

  return ok({ threadId: thread.id }, 201);
}
