import { getLocale } from "./i18n";

/**
 * Quran text, fetched straight from alquran.cloud — the same source and the
 * same edition identifiers the web reader uses, so a mosque sees identical
 * text in both products.
 *
 * Audio streams from the islamic.network CDN, the same source as the web
 * reader. Playback itself needs `expo-audio` — a native module, so a client
 * built before it was added has to be rebuilt (AGENTS.md §8).
 *
 * Not routed through `/api/v1`: this is public scripture with no tenant
 * scoping, and going direct keeps it working without a session. Personal
 * bookmarks are the opposite — those go through the API, under RLS.
 */
const BASE = "https://api.alquran.cloud/v1";

export const ARABIC_EDITION = "quran-uthmani";

export type SurahMeta = {
  number: number;
  name: string;
  englishName: string;
  englishNameTranslation: string;
  numberOfAyahs: number;
  revelationType: string;
};

export type Ayah = {
  number: number;
  text: string;
  numberInSurah: number;
  juz: number;
  page: number;
};

export type SurahData = SurahMeta & { ayahs: Ayah[] };

/** Matches `defaultTranslationForLocale` in the web app — keep in step. */
export function translationForLocale(locale: string = getLocale()): string {
  switch (locale) {
    case "de":
      return "de.aburida";
    case "tr":
      return "tr.diyanet";
    case "bs":
      return "bs.mlivo";
    default:
      return "en.sahih";
  }
}

/**
 * The surah list is fixed scripture metadata — it never changes, so it is
 * fetched once per app run and kept.
 */
let surahListCache: SurahMeta[] | null = null;

export async function fetchSurahList(): Promise<SurahMeta[]> {
  if (surahListCache) return surahListCache;
  const res = await fetch(`${BASE}/surah`);
  if (!res.ok) throw new Error("surah_list_failed");
  const json = (await res.json()) as { data: SurahMeta[] };
  surahListCache = json.data;
  return json.data;
}

const surahCache = new Map<string, { arabic: SurahData; translation: SurahData }>();

export async function fetchSurah(
  number: number,
  translationEdition = translationForLocale(),
): Promise<{ arabic: SurahData; translation: SurahData }> {
  const key = `${number}:${translationEdition}`;
  const hit = surahCache.get(key);
  if (hit) return hit;

  const editions = [ARABIC_EDITION, translationEdition].join(",");
  const res = await fetch(`${BASE}/surah/${number}/editions/${editions}`);
  if (!res.ok) throw new Error("surah_failed");
  const json = (await res.json()) as { data: SurahData[] };

  const [arabic, translation] = json.data;
  const value = { arabic, translation };
  surahCache.set(key, value);
  return value;
}

/* ── Recitation ───────────────────────────────────────────────────────── */

const AUDIO_CDN = "https://cdn.islamic.network/quran/audio";

export type Bitrate = 128 | 64;

export type Reciter = {
  /** islamic.network audio edition identifier. */
  id: string;
  name: string;
  /** Bitrate folders this reciter actually has, preferred first. */
  bitrates: Bitrate[];
  /**
   * Portrait, from `assets/reciters`. A `require()` id, not a path — Metro
   * resolves these at build time, so the file must be a literal.
   *
   * The images live in `assets/`, **not** in `ios/Mekteb/Reciters`: `ios/` is
   * generated by `expo prebuild`, is gitignored, and `--clean` deletes it —
   * assets kept there vanish on the next rebuild and never reach Android.
   *
   * Optional: two reciters have no portrait yet and fall back to initials.
   */
  image?: number;
};

/**
 * Kept in step with `RECITERS` in `apps/web/src/lib/quran-api.ts`, including
 * the bitrates: availability differs per reciter on the CDN, and asking for a
 * folder a reciter does not have is a 404, not a quieter file.
 */
export const RECITERS: Reciter[] = [
  {
    id: "ar.alafasy",
    name: "Mishary Rashid Alafasy",
    bitrates: [128, 64],
    image: require("../../assets/reciters/reciter-alafasy.png"),
  },
  {
    id: "ar.abdulbasitmurattal",
    name: "Abdul Basit (Murattal)",
    bitrates: [64],
    image: require("../../assets/reciters/reciter-abdulbasit.png"),
  },
  {
    id: "ar.abdurrahmaansudais",
    name: "Abdurrahman As-Sudais",
    bitrates: [64],
    image: require("../../assets/reciters/reciter-sudais.png"),
  },
  {
    id: "ar.husary",
    name: "Mahmoud Khalil Al-Husary",
    bitrates: [128, 64],
    image: require("../../assets/reciters/reciter-husary.png"),
  },
  {
    id: "ar.minshawi",
    name: "Mohamed Siddiq El-Minshawi",
    bitrates: [128],
    image: require("../../assets/reciters/reciter-minshawi.png"),
  },
  {
    id: "ar.shaatree",
    name: "Abu Bakr Ash-Shaatree",
    bitrates: [128, 64],
    image: require("../../assets/reciters/reciter-shatri.png"),
  },
  // Added with the portraits — both verified against the CDN, including which
  // bitrate folders exist (asking for the wrong one is a 403, not a quieter
  // file: Shuraym has no 128 kbps).
  {
    id: "ar.mahermuaiqly",
    name: "Maher Al Muaiqly",
    bitrates: [128, 64],
    image: require("../../assets/reciters/reciter-muaiqly.png"),
  },
  {
    id: "ar.saoodshuraym",
    name: "Saood Ash-Shuraym",
    bitrates: [64],
    image: require("../../assets/reciters/reciter-shuraim.png"),
  },
  // No portrait yet — the picker falls back to initials.
  { id: "ar.muhammadayyoub", name: "Muhammad Ayyoub", bitrates: [128] },
  { id: "ar.hudhaify", name: "Ali Al-Hudhaify", bitrates: [128, 64] },
];

export const DEFAULT_RECITER = "ar.alafasy";

/**
 * Candidate URLs for one ayah, built from its **global** number (1…6236) —
 * `Ayah.number`, not `numberInSurah`. Nothing is fetched to switch reciter.
 */
export function audioUrlsForAyah(globalAyahNumber: number, reciterId: string): string[] {
  const reciter = RECITERS.find((r) => r.id === reciterId) ?? RECITERS[0];
  return reciter.bitrates.map(
    (b) => `${AUDIO_CDN}/${b}/${reciter.id}/${globalAyahNumber}.mp3`,
  );
}

/** `GET/POST/DELETE /quran/saved-ayahs` — personal, per user, never per mosque. */
export type SavedAyah = {
  id: string;
  surahNumber: number;
  ayahNumber: number;
  surahName: string;
  arabicText: string;
  translationText: string | null;
  translationEdition: string | null;
  note: string | null;
  createdAt: string;
};
