import { existsSync } from "node:fs";
import type { ExpoConfig } from "expo/config";

/** True when the Firebase android config is present (created in the Firebase
 *  console, package `de.mekteb.app`). Drives whether expo-notifications wires
 *  FCM at prebuild time. */
const existsGoogleServices = () =>
  existsSync(new URL("./google-services.json", import.meta.url));

/**
 * `apiBaseUrl` is read at runtime from `extra`, so the same build can point at
 * local, staging or production. On a physical device `localhost` is the phone
 * itself — set EXPO_PUBLIC_API_URL to your machine's LAN address.
 */
const apiBaseUrl =
  process.env.EXPO_PUBLIC_API_URL ?? "http://localhost:3000";

const config: ExpoConfig = {
  name: "Mekteb",
  slug: "mekteb",
  scheme: "mekteb",
  version: "0.1.0",
  orientation: "portrait",
  userInterfaceStyle: "automatic",
  /**
   * Generated by `scripts/make-icons.py` — placeholders with intent, not final
   * art. Regenerate rather than hand-editing the PNGs.
   */
  icon: "./assets/icon.png",
  ios: {
    supportsTablet: true,
    bundleIdentifier: "de.mekteb.app",
    ...(process.env.APPLE_TEAM_ID
      ? { appleTeamId: process.env.APPLE_TEAM_ID }
      : {}),
    // The app half of the widget channel; the extension declares the same
    // group in targets/widget/expo-target.config.js.
    entitlements: {
      "com.apple.security.application-groups": ["group.de.mekteb.app"],
    },
  },
  android: {
    package: "de.mekteb.app",
    adaptiveIcon: {
      // Transparent foreground on a flat green plate: Android masks the icon
      // to whatever shape the launcher uses, and a baked-in background would
      // be cropped along with the art.
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: "#15803d",
    },
  },
  plugins: [
    "expo-router",
    "expo-secure-store",
    // Widgets are native and need a prebuild, so this app cannot run in Expo
    // Go. `expo-dev-client` is present from the start rather than added later
    // — see AGENTS.md §8.
    "expo-dev-client",
    /**
     * Quran recitation. The plugin is configured without microphone access:
     * the app only ever plays audio, and asking a family for the microphone
     * to listen to the Quran is both wrong and an App Store review question
     * nobody should have to answer.
     *
     * **Both flags are needed.** `microphonePermission` is the iOS half
     * (`NSMicrophoneUsageDescription`); Android is governed by
     * `recordAudioAndroid`, which defaults to *true* — so with the iOS flag
     * alone the first Android prebuild wrote `android.permission.RECORD_AUDIO`
     * into the manifest, which is exactly what this comment says not to do.
     */
    [
      "expo-audio",
      { microphonePermission: false, recordAudioAndroid: false },
    ] as [string, unknown],
    /**
     * Home-screen widgets. The extension is a *signed* target, so it needs an
     * Apple team id and an App Group registered on that account — set
     * `APPLE_TEAM_ID` before prebuilding. Without it the plugin is skipped
     * entirely, so `expo run:ios` still works for anyone who just wants the
     * app (the JS side degrades to "this build has no widgets").
     */
    ...(process.env.APPLE_TEAM_ID
      ? [
          [
            "@bacons/apple-targets",
            { appleTeamId: process.env.APPLE_TEAM_ID },
          ] as [string, unknown],
        ]
      : []),
    /**
     * Android widgets (open.md §3.4). The plugin registers the receiver,
     * provider XML and collection service in the manifest at prebuild time.
     * The widget itself renders through `react-native-android-widget`'s
     * headless task (see `src/widgets/`), fed by the same payload the iOS
     * widget reads — `widget-format.ts` stays the single source of strings.
     */
    [
      "react-native-android-widget",
      {
        widgets: [
          {
            name: "MektebWidget",
            minWidth: "180dp",
            minHeight: "110dp",
            targetCellWidth: 4,
            targetCellHeight: 2,
            resizeMode: "horizontal|vertical",
            label: "Mekteb",
            description: "Mekteb — Nächste Aufgabe und Unterricht",
          },
        ],
      },
    ] as [string, unknown],
    /**
     * Push. The plugin is what adds the iOS push entitlement and the Android
     * notification assets at prebuild time — the JS module alone does not.
     *
     * On Android, `googleServicesFile` points at `google-services.json` from
     * the Firebase project (package `de.mekteb.app`). It is wired only when
     * the file exists, so a prebuild without it still works — but without it
     * the app cannot register an FCM token and Android pushes never arrive.
     */
    [
      "expo-notifications",
      {
        ...(existsGoogleServices()
          ? { googleServicesFile: "./google-services.json" }
          : {}),
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  extra: {
    apiBaseUrl,
    eas: {
      projectId: "10b7ad70-de00-11e9-8b9c-8d650f9b19f6",
    },
  },
};

export default config;
