export interface BlockItem {
  type: "h" | "p" | "b" | "num" | "img";
  level?: number;
  text?: string;
  url?: string;
  caption?: string;
}

export function bnH(text: string, level = 2) {
  return {
    id: crypto.randomUUID(),
    type: "heading",
    props: {
      level,
      textColor: "default",
      backgroundColor: "default",
      textAlignment: "left",
      isToggleable: false,
    },
    content: [{ type: "text", text, styles: {} }],
    children: [],
  };
}

export function bnP(text: string) {
  return {
    id: crypto.randomUUID(),
    type: "paragraph",
    props: {
      textColor: "default",
      backgroundColor: "default",
      textAlignment: "left",
    },
    content: [{ type: "text", text, styles: {} }],
    children: [],
  };
}

export function bnBullet(text: string) {
  return {
    id: crypto.randomUUID(),
    type: "bulletListItem",
    props: {
      textColor: "default",
      backgroundColor: "default",
      textAlignment: "left",
    },
    content: [{ type: "text", text, styles: {} }],
    children: [],
  };
}

export function bnNum(text: string) {
  return {
    id: crypto.randomUUID(),
    type: "numberedListItem",
    props: {
      textColor: "default",
      backgroundColor: "default",
      textAlignment: "left",
    },
    content: [{ type: "text", text, styles: {} }],
    children: [],
  };
}

export function bnImage(url: string, caption?: string) {
  return {
    id: crypto.randomUUID(),
    type: "image",
    props: {
      backgroundColor: "default",
      textAlignment: "center",
      name: url.split("/").pop() || "image.jpg",
      url,
      caption: caption || "",
      showPreview: true,
      previewWidth: 512,
    },
    children: [],
  };
}

export function germanBlocksToBlockNote(blocks: BlockItem[]) {
  return blocks.map((b) => {
    if (b.type === "h") return bnH(b.text ?? "", b.level || 2);
    if (b.type === "p") return bnP(b.text ?? "");
    if (b.type === "b") return bnBullet(b.text ?? "");
    if (b.type === "num") return bnNum(b.text ?? "");
    if (b.type === "img") return bnImage(b.url ?? "", b.caption);
    return bnP(b.text ?? "");
  });
}

export const TOPICS = [
  {
    key: "topic_1",
    title: "Ilmihal 1: Uvod u mekteb i islamsko ponašanje",
    description: "Uvodne dove, čistoća, bonton, zahvalnost i prva sura El-Fatiha",
    sort_order: 1,
  },
  {
    key: "topic_2",
    title: "Ilmihal 1: Imanski šarti (Islamsko vjerovanje)",
    description: "Pregled 33 šarta, šest temelja imana, meleki, objave, poslanici, Muhammed a.s., Sudnji dan i Kader",
    sort_order: 2,
  },
  {
    key: "topic_3",
    title: "Ilmihal 1: Islamski šarti (Islamske dužnosti)",
    description: "Pet stubova islama: Šehadet, namaz, ramazanski post, zekat i hadž, te sure Felek, Nas i Leheb",
    sort_order: 3,
  },
];

export const BOSNIAN_LESSONS = [
  // ── TOPIC 1 ──
  {
    topic_key: "topic_1",
    title: "E'uzubila i Bismila",
    sort_order: 1,
    blocks: [
      bnH("E'uzubila", 2),
      bnP("Prve riječi koje ćemo naučiti su:"),
      bnH("E'ŪZUBILLĀHI MINEŠ-ŠEJTĀNIR-RADŽĪM", 3),
      bnP("Ove riječi znače: „Tražim od Allaha da me zaštiti od prokletog šejtana.”"),
      bnP("Ove riječi izgovaramo:"),
      bnBullet("da bismo bili sigurni"),
      bnBullet("da lahko i dobro učimo"),
      bnBullet("da se sretno igramo"),
      bnBullet("da mirno spavamo i lijepo sanjamo"),
      bnH("Bismila", 2),
      bnP("S kojim riječima počinjemo svaki dobar posao? To su riječi koje svaki musliman i muslimanka trebaju znati:"),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("Naučimo značenje ovih riječi: „U ime Allaha, Milostivog, Samilosnog!”"),
      bnH("Kada se uče E'uzubila i Bismila?", 2),
      bnBullet("Kada jedemo i pijemo"),
      bnBullet("Kada učimo i čitamo"),
      bnBullet("Kada vozimo bicikl"),
      bnBullet("Kada ulazimo u auto"),
      bnBullet("Kada ulazimo u kuću"),
      bnBullet("Kada hoćemo spavati"),
      bnBullet("Prije igranja"),
      bnBullet("Kada oblačimo odjeću"),
      bnP("Osim ovoga, E'uzubila i Bismila se izgovaraju i u mnogim drugim situacijama. Pitaj muallima kada se još izgovaraju E'uzubila i Bismila."),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Čovjek je najljepše Allahovo stvorenje",
    sort_order: 2,
    blocks: [
      bnH("Čovjek je najljepše Allahovo stvorenje", 2),
      bnP("Allah, dželle šanuhu, je stvorio cijeli svijet:"),
      bnBullet("Čovjeka"),
      bnBullet("Biljke"),
      bnBullet("Životinje"),
      bnBullet("Zemlju"),
      bnBullet("Nebo"),
      bnBullet("Kosmos"),
      bnP("U Kur'anu Časnom Uzvišeni Allah poručuje:"),
      bnH("„Čovjeka smo stvorili u najljepšem obliku”", 3),
      bnP("(Kur'an, sura Et-Tin, 4)"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Ja u mekteb idem i dove za početak",
    sort_order: 3,
    blocks: [
      bnH("Ja u mekteb idem", 2),
      bnP("Mekteb je mala škola kod džamije ili u džamiji. U mektebu se igramo i učimo:"),
      bnBullet("o islamskom vjerovanju"),
      bnBullet("o islamskim dužnostima"),
      bnBullet("o islamskom ponašanju"),
      bnH("U mekteb nosimo:", 3),
      bnBullet("Ilmihal"),
      bnBullet("Svesku"),
      bnBullet("Olovku"),
      bnBullet("Gumicu"),
      bnBullet("Ranac"),
      bnH("Dove za hairli početak", 2),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnH("RABBI JESSIR VE LĀ TUASSIR, RABBI TEMMIM BIL-HAJR. ĀMĪN.", 3),
      bnP("Bože, olakšaj a ne otežaj. Bože, završi s dobrim. Amin!"),
      bnH("RABBI ZIDNĪ ILMĀ", 3),
      bnP("Gospodaru moj, povećaj mi znanje."),
      bnH("Žuri Mirza na pouku", 3),
      bnP("Osvanuo sretan dan,\nide Mirza razdragan.\nPoskakuje — svi to vide,\nna pouku Mirza ide.\n\nU ruci mu torbica,\nu torbici sveščica,\ni udžbenik Ilmihal,\nprva riječ mu — Bismillah.\n\n(R. Kadić)"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Vjera islam i Kelime-i-šehadet",
    sort_order: 4,
    blocks: [
      bnH("Vjera islam", 2),
      bnP("Naša vjera se zove islam."),
      bnH("Šta je islam?", 3),
      bnP("Islam je vjera koju je Uzvišeni Allah preko Svoga poslanika Muhammeda, alejhiselam, objavio cijelom čovječanstvu."),
      bnH("Šta znači islam?", 3),
      bnP("Islam znači pokornost Allahu, dželle šanuhu."),
      bnH("U čemu se sastoji pokornost Uzvišenom Allahu?", 3),
      bnP("Musliman i muslimanka vjeruju u Allaha, izvršavaju islamske propise i dužnosti i rade ono što je dobro. Lijepo se ponašaju, govore istinu i pomažu drugima."),
      bnP("„Islam je kao sunce,\nkad ti jednom takne srce,\nčitav svijet zavoliš,\nnikog više ne mrziš.”\n(R. Kadić)"),
      bnH("Kelime-i-šehadet", 2),
      bnP("Kelime-i-šehadetom svjedočimo da smo muslimani."),
      bnH("Kako glasi Kelime-i-šehadet?", 3),
      bnH("EŠHEDU EN LĀ ILĀHE ILLALLĀH, VE EŠHEDU ENNE MUHAMMEDEN 'ABDUHŪ VE RESŪLUHŪ.", 3),
      bnP("Prijevod: „Vjerujem i svjedočim da nema božanstva osim Allaha i vjerujem i svjedočim da je Muhammed, alejhiselam, Allahov rob i poslanik!”"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Selam — Islamski pozdrav",
    sort_order: 5,
    blocks: [
      bnH("Selam — Islamski pozdrav", 2),
      bnP("Selam je međusobni pozdrav muslimana."),
      bnH("Kako se naziva i odgovara selam?", 3),
      bnP("Pozdrav: Es-selamu alejkum!\nOdgovor: Alejkumus-selam!"),
      bnP("Značenje: Neka je na Vas Božiji mir i spas!"),
      bnP("„Es-selamu alejkum nek se čuje sa svih strana,\nselam selam, mahsuz selam, glas je mira muslimana.”"),
      bnH("Kada i kome nazivamo selam?", 3),
      bnBullet("Selam nazivamo pri ulasku i izlasku iz kuće"),
      bnBullet("Selamimo muslimane i muslimanke na ulici"),
      bnBullet("Selam prvi nazivamo starijim osobama"),
      bnBullet("Muškarci prvi nazivaju selam"),
      bnBullet("Selam nazivamo kada dolazimo u društvo ili odlazimo iz društva"),
      bnP("Sa muallimom, kroz igru, uvježbajte selam u raznim prilikama!"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Čistoća u islamu",
    sort_order: 6,
    blocks: [
      bnH("Čistoća", 2),
      bnP("Čistoća je pola zdravlja. Zato se trebamo brinuti o higijeni našeg tijela i odjeće."),
      bnP("Voda je Allahov dar ljudima koji koristimo za piće, spremanje hrane, pranje tijela i odjeće."),
      bnP("Allah voli urednost i čistoću i muslimani uvijek trebaju biti uredni i čisti."),
      bnP("Muhammed, alejhiselam, je rekao: „Čistoća je dio vjere.”"),
      bnH("U ličnu higijenu se ubraja:", 3),
      bnBullet("Pranje ruku prije i poslije jela"),
      bnBullet("Redovno kupanje"),
      bnBullet("Redovno pranje zuba"),
      bnBullet("Redovno skraćivanje noktiju"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Voda je Allahov dar",
    sort_order: 7,
    blocks: [
      bnH("Voda je Allahov dar", 2),
      bnP("Uobičajen ljetni dan. Sejid se sa djecom igrao u dvorištu džamije. Napustivši igru, utrča u kuću:"),
      bnP("„Majko, ožednio sam, mogu li dobiti čašu vode?”"),
      bnP("Zahvalivši se, upita:"),
      bnP("„Daje li nam i vodu Allah, dželle šanuhu? Kako je lijepo kada se ugasi žeđ. Sigurno se svi tako osjećaju?”"),
      bnP("„Da, Sejide, da bi insan zadovoljio svoje potrebe, Allah, dž.š., mu daruje i vodu, koja je izvor svega.”"),
      bnP("„On daje vodu i mome mačku?” — upita. Majka potvrdno klimnu glavom."),
      bnP("„I pticama, zečevima, jagnjadima i drugim životinjama?”"),
      bnP("„Da, Sejide. Allah, dž.š., je svim stvorenjima darovao vodu da bi ugasili žeđ i zadovoljili druge potrebe: i biljkama, i drveću, i svemu što je živo. Svemu što zavisi od nje, On daje vodu.”"),
      bnP("„Pada li zbog toga kiša?” — upita Sejid — „Jer kad pada kiša, ja se ne mogu igrati u avliji, ali sada znam da se zemlja i biljke raduju kiši.”"),
      bnP("Milujući ga po glavi, majka nastavi:"),
      bnP("„Da, sine, u pravu si, oni vole kišu. Vidiš li nebo? Primjećuješ li guste oblake? Oni donose kišu, znaš li to? Vidi, već počinju padati prve kapi kiše. Možeš li mi pomoći da zatvorim prozore?”"),
      bnP("Dječak pristade, veselo govoreći:"),
      bnP("„Majko, kiša će padati veoma dugo i sve će se biljke napiti vode. A šta se događa sa onim dijelom koji ostaje na površini zemlje?”"),
      bnP("„Šta se dešava sa svakom kapi kiše — ne znam, ali znam da se jedan dio skuplja u izvore. Iz tih izvora se voda crpi prečišćena, a zatim salijeva u vodovodne cijevi koje dovode u kuće vodu koju mi koristimo.”"),
      bnP("Dječak prekide majku:"),
      bnP("„Da nema vode, kako bih se kupao? Majko, kako je samo voda potrebna svima! Allah, dž.š., naš Gospodar, velikodušan je jer nam vodu daruje!”"),
      bnP("Voda je Allahov dar!"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Desna strana u islamu",
    sort_order: 8,
    blocks: [
      bnH("Desna strana", 2),
      bnP("Islam daje prednost desnoj strani i zato sve lijepe poslove radimo desnom rukom i nogom!"),
      bnBullet("Desnom rukom jedemo i pijemo"),
      bnBullet("Prvo oblačimo desni rukav"),
      bnBullet("Prvo obuvamo desnu cipelu"),
      bnBullet("Liježemo na desnu stranu"),
      bnBullet("Desnom nogom ulazimo u kuću i džamiju"),
      bnBullet("Lijevom nogom izlazimo iz kuće"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Hrana i piće — Halal i haram",
    sort_order: 9,
    blocks: [
      bnH("Hrana i piće", 2),
      bnP("Allah, dž.š., je stvorio čovjeka i podario mu nafaku kojom će se hraniti. Dozvolio mu je sva lijepa, ukusna jela i pića, a zabranio ružna koja mu nanose štetu."),
      bnH("Ono što je HALAL — DOZVOLJENO:", 3),
      bnBullet("Zec, ovca, krava, kokoška, riba"),
      bnBullet("Voće, povrće, žitarice i mliječni proizvodi"),
      bnH("Ono što je HARAM — ZABRANJENO:", 3),
      bnBullet("Svinjsko meso i prerađevine"),
      bnBullet("Pas, orao, žaba i meso grabljivica"),
      bnBullet("Alkohol i opojna pića"),
      bnH("Prilikom jela i pića treba voditi računa da:", 3),
      bnBullet("prije i poslije jela peremo ruke"),
      bnBullet("prije jela proučimo Bismilu i jedemo desnom rukom"),
      bnBullet("ne jedemo suviše vrelu hranu"),
      bnBullet("jedemo zajedno sa porodicom"),
      bnBullet("nakon jela, zahvalimo Allahu riječima El-hamdu lillāh"),
      bnBullet("raspremimo sofru poslije jela"),
      bnBullet("nakon jela peremo zube"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Subhaneke i zahvalnost Allahu",
    sort_order: 10,
    blocks: [
      bnH("Subhaneke", 2),
      bnP("Uzvišenom Allahu zahvaljujemo učeći dovu Subhaneke:"),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnH("SUBHĀNEKE ALLĀHUMME VE BI HAMDIKE, VE TEBĀREKESMUKE, VE TE'ĀLĀ DŽEDDUKE, VE LĀ ILĀHE GAJRUKE.", 3),
      bnP("Prijevod: „Nek si slavljen samo Ti, moj Allahu, i Tebi hvala, Tvoje je ime blagoslovljeno, Tvoje je veličanstvo uzvišeno, Nema drugog boga, osim Tebe.”"),
      bnH("Allahu uvijek trebamo biti zahvalni", 2),
      bnP("Sejid je bio u šetnji sa svojim babom. Kada su se vratili, trčeći uđe u kuću i zagrli majku. Od sreće zavika: „Majko, šta sam sve vidio: male ptice, mačiće, piliće i ne mogu ti sve nabrojati!”"),
      bnP("„Sine, drago mi je što ti se sve to dopalo.”"),
      bnP("„Do sada se nisam nikada tako zabavljao.”"),
      bnP("„Lice ti prosto sija od sreće.” — reče majka."),
      bnP("Dječak sjede pored majke: „Majko, kako nam je Allah, dž.š., darovao lijep svijet!”"),
      bnP("„Da sine, Allah, dž.š., je, doista, stvorio veoma lijep svijet.”"),
      bnP("„Onda i mi moramo biti s onima koji su na Pravom putu i tako iskazati našu zahvalnost!”"),
      bnP("„Sejide, slažem se sa tobom, jer mi smo zaduženi za očuvanje ove ljepote koju nam je Allah, dž.š., dao na povjerenje. Svojim djelima trebamo pokazati da smo dobri robovi svome Gospodaru i trebamo opravdati dato nam povjerenje.”"),
      bnP("„Ako budete zahvalni, Ja ću vam, zacijelo, još više dati; budete li nezahvalni, kazna Moja doista će stroga biti.” (Kur'an, sura Ibrahim, 7)"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Sura El-Fatiha",
    sort_order: 11,
    blocks: [
      bnH("Sura El-Fatiha", 2),
      bnP("Fatiha je prva sura u Kur'anu."),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("EL-HAMDU LILLĀHI RABBIL-'ĀLEMĪN.\nER-RAHMĀNIR-RAHĪM.\nMĀLIKI JEVMID-DĪN.\nIJJĀKE N'ABUDU VE IJJĀKE NESTE'ĪN.\nIHDINES-SIRĀTAL-MUSTEKĪM.\nSIRĀTALLEZĪNE EN'AMTE 'ALEJHIM,\nGAJRIL-MAGDŪBI 'ALEJHIM VE LED-DĀLLĪN. ĀMĪN!"),
      bnH("Prijevod:", 3),
      bnP("Hvala Allahu, Gospodaru svjetova,\nMilostivom, Samilosnom, Vladaru Sudnjega dana.\nSamo Tebe obožavamo i samo od Tebe pomoć tražimo.\nUputi nas na Pravi put.\nNa Put onih kojima si dao svoje blagodati,\na ne na put onih koji su protiv sebe srdžbu izazvali,\nniti onih koji su zalutali. Amin!"),
      bnP("„Fatiha je prva sura iz Kur'ana,\nduhovna je hrana svakog muslimana,\nsvaki vjernik i vjernica ovu suru neka uči\ni sa njom se Allahovoj uputi prikuči.”"),
    ],
  },
  {
    topic_key: "topic_1",
    title: "Ponavljanje gradiva — Uvodni dio",
    sort_order: 12,
    blocks: [
      bnH("Ponavljanje je majka znanja", 2),
      bnP("Do sada smo naučili: E'uzubilu i Bismilu, Rabbi jessir, Kelime-i-šehadet, Subhaneke i Fatihu. Provjerite da li znate:"),
      bnNum("Prouči E'uzubilu!"),
      bnNum("Prouči Bismilu!"),
      bnNum("Kako počinjemo svaki dobar posao?"),
      bnNum("Ko je najljepše Allahovo stvorenje?"),
      bnNum("O čemu učimo u mektebu?"),
      bnNum("Prouči dovu Rabbi jessir!"),
      bnNum("Kako se zove naša vjera?"),
      bnNum("Šta je islam?"),
      bnNum("Čime potvrđujemo našu pripadnost islamu?"),
      bnNum("Kako glasi Kelime-i-šehadet?"),
      bnNum("Kako se zove islamski pozdrav?"),
      bnNum("Kako se pozdravljamo i kako otpozdravljamo?"),
      bnNum("Kome se trebamo zahvaljivati?"),
      bnNum("Kako zahvaljujemo Uzvišenom Allahu?"),
      bnNum("Kako glasi prva sura u Kur'anu?"),
    ],
  },

  // ── TOPIC 2 ──
  {
    topic_key: "topic_2",
    title: "Pregled 33 šarta — Uvjeta u islamu",
    sort_order: 13,
    blocks: [
      bnH("Pregled 33 šarta — Uvjeta u islamu", 2),
      bnP("Treba znati da ima samo jedan Bog. On je Stvoritelj i Gospodar svih svjetova. Stvorio je čovjeka u najljepšem obliku i darovao mu razum. Razum je taj koji slijedi Božiju uputu i pokorava se Božijoj volji."),
      bnP("Temelj islama je Kelime-i-šehadet kojim svjedočimo našu vjeru. Međutim, nije dovoljno samo vjerovati, nego je potrebno islamske dužnosti izvršavati."),
      bnH("Islam se temelji na 33 šarta:", 3),
      bnH("Imanski šarti (6):", 3),
      bnNum("Āmentu billāhi (Ja vjerujem u Allaha)"),
      bnNum("Ve melāiketihī (I vjerujem u Njegove meleke)"),
      bnNum("Ve kutubihī (I vjerujem u Njegove Knjige)"),
      bnNum("Ve rusulihī (I vjerujem u Njegove poslanike)"),
      bnNum("Vel-jevmil-āhiri (I vjerujem u Sudnji dan)"),
      bnNum("Ve bil-kaderi hajrihī ve šerrihī minellāhi te'ālā (I vjerujem da sve što se događa, dobro i zlo, biva Allahovom voljom i određenjem)"),
      bnH("Islamski šarti (5):", 3),
      bnNum("Kelime-i-šehadet (Očitovanje pripadnosti islamu)"),
      bnNum("Klanjati propisane namaze"),
      bnNum("Ramazan postiti"),
      bnNum("Zekat davati"),
      bnNum("Hadž obaviti"),
      bnH("Abdeski šarti (4):", 3),
      bnNum("Oprati lice"),
      bnNum("Oprati obje ruke do iza laktova"),
      bnNum("Potrati mokrom rukom četvrtinu glave (mesh)"),
      bnNum("Oprati noge do članaka"),
      bnH("Gusulski šarti (3):", 3),
      bnNum("Isprati usta"),
      bnNum("Isprati nos"),
      bnNum("Oprati cijelo tijelo"),
      bnH("Tejemumski šarti (2):", 3),
      bnNum("Izgovoriti nijet"),
      bnNum("Dotaknuti dlanovima čistu suhu zemlju i potrati lice, zatim ponovo dotaknuti zemlju i potrati obje ruke do iza laktova"),
      bnH("Namaski šarti — Prije namaza (6 uvjeta):", 3),
      bnNum("Da bude čisto tijelo, odijelo i mjesto gdje se klanja"),
      bnNum("Uzeti abdest"),
      bnNum("Propisno se obući (pokriti avret)"),
      bnNum("Na vrijeme klanjati"),
      bnNum("Okrenuti se prema Kibli"),
      bnNum("Zanijetiti (donijeti odluku za namaz)"),
      bnH("Namaski šarti — U toku namaza (6 ruknova):", 3),
      bnNum("Iftitahi-tekbir (Početni tekbir)"),
      bnNum("Kijam (Stajanje u namazu)"),
      bnNum("Kiraet (Učenje Kur'ana)"),
      bnNum("Ruku' (Pregib u namazu)"),
      bnNum("Sedžda"),
      bnNum("Ka'dei-ehire (Zadnje sjedenje u namazu)"),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Imanski šarti — Islamsko vjerovanje",
    sort_order: 14,
    blocks: [
      bnH("Imanski šarti (Islamsko vjerovanje)", 2),
      bnP("Islamsko vjerovanje, iman, sastoji se od šest temeljnih istina vjere ili šest imanskih šarta:"),
      bnNum("ĀMENTU BILLĀHI — Ja vjerujem u Allaha"),
      bnNum("VE MELĀIKETIHĪ — I vjerujem u Njegove meleke"),
      bnNum("VE KUTUBIHĪ — I vjerujem u Njegove Knjige"),
      bnNum("VE RUSULIHĪ — I vjerujem u Njegove poslanike"),
      bnNum("VEL-JEVMIL-ĀHIRI — I vjerujem u Sudnji dan"),
      bnNum("VE BIL-KADERI HAJRIHĪ VE ŠERRIHĪ MINELLĀHI TE'ĀLA — I vjerujem da sve što se događa, dobro i zlo, biva Allahovom voljom i određenjem"),
      bnH("Stihovi o imanskim šartima", 3),
      bnP("AMENTU BILLAHI:\nJa vjerujem u jednog Boga,\nKoji stvori svakog roba.\nOn sazda svemir cijeli\nda se samo Njemu divi.\n\nVE MELAIKETIHI:\nI vjerujem sve meleke,\nBez grijeha i bez mane.\nTako ih Bog stvori,\nNurom obasjane.\n\nVE KUTUBIHI:\nI vjerujem u Kitabe,\nto su riječi Uzvišenog.\nČetiri su odabrane,\nKur'anom potvrđene.\n\nVE RUSULIHI:\nI vjerujem u poslanike,\nAllahove miljenike.\nVjeru su nam dostavili,\nsvakom dobru podučili.\n\nVEL-JEVMIL-AHIRI:\nI vjerujem u Sudnji dan,\nkad će djela na mizan.\nOd Vatre se treba spasiti\ni u Džennetu se skrasiti.\n\nVA BIL-KADERI HAJRIHI VE ŠERRIHI MINELLAHI TE'ALA:\nI vjerujem da sve što se događa,\nšto umire i što se rađa,\nšto noć krije a dan otkriva,\nAllahovom voljom biva.\n\n(E. Nurović)"),
      bnP("Imanske šarte treba znati i u njih čvrsto vjerovati. Ko ih zna i vjeruje srcem i jezikom on je vjernik — musliman."),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Prvi imanski šart: Āmentu billāhi i Sura Ihlas",
    sort_order: 15,
    blocks: [
      bnH("Prvi imanski šart", 2),
      bnH("ĀMENTU BILLĀHI — JA VJERUJEM U ALLAHA, DŽELLE ŠANUHU", 3),
      bnP("Razmišljanjem o onom što nas okružuje, razum nas dovodi do uvjerenja da mora postojati neko savršen i moćan ko je sve stvorio i ko svim vlada i upravlja. To je Svemogući Allah, dželle šanuhu. Allah je stvoritelj i Gospodar svega što vidimo i što ne vidimo."),
      bnP("Allah je stvorio Zemlju i nebo, životinje i biljke. Stvorio je čovjeka u najljepšem obliku."),
      bnP("Kada spomenemo Božije ime Allah, treba da kažemo: dželle šanuhu, što znači: Uzvišeni ili Svevišnji, a skraćeno se piše: dž.š."),
      bnH("Suretul-Ihlas", 2),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("KUL HUVALLĀHU EHAD.\nALLĀHUS-SAMED.\nLEM JELID VE LEM JŪLED\nVE LEM JEKUN LEHŪ KUFUVEN EHAD."),
      bnH("Prijevod:", 3),
      bnP("Reci: „Allah je jedan.\nAllah je utočište svemu.\nNije rodio i rođen nije,\ni niko Mu ravan nije.”"),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Drugi imanski šart: Ve melāiketihī (Meleki)",
    sort_order: 16,
    blocks: [
      bnH("Drugi imanski šart", 2),
      bnH("VE MELĀIKETIHĪ — VJERUJEM U ALLAHOVE MELEKE", 3),
      bnP("Meleki su razumna, duhovna, nevidljiva bića. Stvoreni su od nura – svjetlosti. Meleki ne griješe, oni slave i veličaju Allaha. Stalno služe Allahu i imaju svoja zaduženja. Nisu muškog ni ženskog spola, ne jedu i ne piju. Meleka ima mnogo, a njihov broj zna samo Allah."),
      bnH("Imena najpoznatijih meleka i njihove dužnosti su:", 3),
      bnBullet("DŽIBRIL: Prenosio je i dostavljao Božije objave poslanicima"),
      bnBullet("MELEK SMRTI (AZRAIL): Rastavlja duše od tijela u času smrti"),
      bnBullet("MIKAIL: Brine se o prirodnim pojavama (vjetru, kiši, rastu bilja)"),
      bnBullet("ISRAFIL: Puhanjem u sur najavit će Kijametski i Sudnji dan"),
      bnBullet("KIRAMEN KATIBIN: Prate ljude, pišu njihova djela i donose im dobre misli"),
      bnBullet("MUNKIR I NEKIR: Ispituju u mezaru svakog čovjeka"),
      bnP("Osim meleka, Allah je stvorio i druga nevidljiva bića, a to su džini i šejtani. Šejtani donose ružne misli i navode na zlo."),
      bnP("Zaštitu od prokletog šejtana tražimo od Allaha, dželle šanuhu, riječima:"),
      bnH("E'ŪZUBILLĀHI MINEŠ-ŠEJTĀNIR-RADŽĪM", 3),
      bnP("Utječem se Allahu od prokletog šejtana."),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Treći imanski šart: Ve kutubihī (Božije knjige)",
    sort_order: 17,
    blocks: [
      bnH("Treći imanski šart", 2),
      bnH("VE KUTUBIHĪ — VJERUJEM U ALLAHOVE KNJIGE — OBJAVE", 3),
      bnP("Allahove Knjige su Objave koje je melek Džibril dostavljao poslanicima, s ciljem da ih prenesu i objasne ljudima. Prva objava dostavljena je prvom čovjeku, Ademu, a.s."),
      bnP("Sve Objave pozivale su ljude da vjeruju u Jednog Boga i da se Njemu pokoravaju. Objavljene su četiri velike Knjige. Bilo je i manjih Objava koje se zovu Suhufi."),
      bnH("Četiri velike Knjige — Objave su:", 3),
      bnBullet("TEVRAT: Objavljen Musau, alejhis-selam"),
      bnBullet("ZEBUR: Objavljen Davudu, alejhis-selam"),
      bnBullet("INDŽIL: Objavljen Isau, alejhis-selam"),
      bnBullet("KUR'AN: Objavljen Muhammedu, alejhis-selam"),
      bnH("Kur'an-i Kerim", 3),
      bnP("Kur'an je posljednja Allahova knjiga koja je preko Muhammeda, a.s., objavljena svim ljudima. U njemu su sadržane upute, savjeti, dove i propisi o islamskom načinu života. Kur'an je putokaz ljudima kako bi bili sretni na ovom i Budućem svijetu. Objavljen je na arapskom jeziku. Objava je trajala 23 godine. Sastoji se od 114 sura."),
      bnP("„Nema bolje knjige od Kur'ana niti ljepše vjere od islama.\nU njemu su mudre riječi što nas vode pravoj sreći.”"),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Četvrti imanski šart: Ve rusulihī (Božiji poslanici)",
    sort_order: 18,
    blocks: [
      bnH("Četvrti imanski šart", 2),
      bnH("VE RUSULIHĪ — VJERUJEM U ALLAHOVE POSLANIKE", 3),
      bnP("Božiji poslanici su odabrani ljudi, koje je Allah, dž.š., iz Svoje milosti slao ljudima, da im dostave i objasne Allahovu Objavu — Uputu. Allah je svakom narodu slao poslanika i zato ih je bilo više, a Kur'an imenom spominje 25."),
      bnP("Prvi čovjek na Zemlji je bio Adem, a.s. On je bio i prvi Božiji poslanik. Posljednji poslanik je Muhammed, a.s., i poslije njega do Sudnjeg dana neće biti poslanika."),
      bnH("Odabrani Božiji poslanici su:", 3),
      bnNum("Ādem, a.s."),
      bnNum("Nūh, a.s."),
      bnNum("Ibrāhīm, a.s."),
      bnNum("Mūsā, a.s."),
      bnNum("Īsā, a.s."),
      bnNum("Muhammed, a.s."),
      bnP("Iza imena poslanika treba dodati: alejhis-selam, što znači: Neka je na njega mir, a skraćeno se piše a.s."),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Muhammed, a.s. — Posljednji Božiji poslanik",
    sort_order: 19,
    blocks: [
      bnH("Muhammed, a.s.", 2),
      bnP("Muhammed, a.s., je posljednji Božiji poslanik. Rođen je 571. godine u Mekki, u plemenu Kurejš. Njegov otac se zvao Abdullah, a majka Amina. Veoma rano ostao je bez roditelja. Od šeste godine brigu o njemu preuzima njegov djed Abdulmuttalib, a potom amidža Ebu Talib."),
      bnP("Allah, dž.š., ga je odabrao za Svoga poslanika i prenosioca posljednje Božije Objave ljudima. U četrdesetoj godini života, primio je prvu Objavu u pećini Hira i postao Božiji poslanik. Nakon trinaest godina, sa muslimanima iz Mekke preseljava se u Medinu i tu ostaje do kraja života. Na Ahiret je preselio u 63. godini u Medini, koja je po njemu dobila ime Medinetun-Nebijj."),
      bnP("Muhammed, a.s., je najodabraniji čovjek i najbolji primjer ljudima kako treba živjeti i vjerovati."),
      bnH("Kasida: Ahmede Muhammede", 3),
      bnP("Moje srce tužno je\nšto ne imade sreće te,\nda druguje uz tebe\nAhmede Muhammede.\n\nKao naj kad zaplače\nmoje oči zarose\nželjne tvoje blizine,\nAhmede Muhammede.\n\nTi si milost Milosnog\nTi si radost srca mog,\nTi si lijek za rane\nAhmede Muhammede.\n\nAškom srce mi gori\nželjno tebe da vidi,\nnaš dragi pejgambere\nAhmede Muhammede.\n\nMojoj duši mehlem je\nkad salavat donese,\nkad ti ime spomene\nAhmede Muhammede."),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Peti imanski šart: Vel-jevmil-āhiri i Sura Kevser",
    sort_order: 20,
    blocks: [
      bnH("Peti imanski šart", 2),
      bnH("VEL-JEVMIL-ĀHIRI — VJERUJEM U SUDNJI DAN", 3),
      bnP("Nakon života na ovome svijetu, koji je prolazan, ljudi će biti proživljeni na Ahiretu, koji je vječan. Sudnji dan je vrijeme kada će ljudi poslije proživljenja na Drugom svijetu odgovarati za svoja djela."),
      bnP("Svakom čovjeku bit će pokazana njegova dobra i loša djela, koja su pisali meleki kiramen katibin."),
      bnP("Ko bude vjerovao u Allaha, dž.š., i činio dobra djela, Božijom milošću bit će uveden u Džennet. U koga bude više loših djela, bit će kažnjen Džehennemom, ako mu Allah, dž.š., ne oprosti. Kada će biti Sudnji dan zna samo Allah, dž.š."),
      bnH("Džennet", 3),
      bnP("Džennet je mjesto na Drugom svijetu u kome će vjernici vječno boraviti i uživati sve blagodati."),
      bnH("Džehennem", 3),
      bnP("Džehennem je mjesto na Drugom svijetu u kome će nevjernici i griješnici, koji su se ogriješili o Božije naredbe ispaštati za svoje grijehe, ukoliko im se Allah ne smiluje i ne oprosti im."),
      bnH("Suretu-l-Kevser", 2),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("INNĀ E'ATAJNĀKEL-KEVSER,\nFE SALLI LI RABBIKE VEN-HAR,\nINNE ŠĀNI'EKE HUVEL-EBTER."),
      bnH("Prijevod:", 3),
      bnP("Mi smo ti, uistinu, mnogo dobro dali,\nzato se Gospodaru svome moli i kurban kolji.\nOnaj koji tebe mrzi sigurno će on bez spomena ostati."),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Šesti imanski šart: Ve bil-kaderi (Kader) i pjesma",
    sort_order: 21,
    blocks: [
      bnH("Šesti imanski šart", 2),
      bnH("VE BIL-KADERI HAJRIHĪ VE ŠERRIHĪ MINELLĀHI TE'ĀLA", 3),
      bnP("Vjerujem da sve što se događa, dobro i loše, biva s Allahovom voljom i Allahovim određenjem."),
      bnP("Allah je stvoritelj svega. On određuje sva zbivanja. Sve što se dešava, biva sa Božijom voljom i određenjem. Ono što Allah hoće to će i biti, a što neće ne može ni biti."),
      bnP("Allah je podario ljudima razum i dao slobodnu volju, mogućnost izbora, da biraju između dobrih i loših djela. Zato čovjek treba nastojati da radi dobra djela. Ako ga zadesi kakva nesreća, treba biti strpljiv. Allahu je poznato sve što je bilo i što će biti."),
      bnH("Rabba traži i uči", 3),
      bnP("Allah, Allah, huve rabbuna, La ilahe illallah.\n\nRabba traži i uči,\nzikrullah ti sve viči,\ndolazit ćeš sve jači,\nLa ilahe illallah.\n\nTi namaza ne puštaj,\ndinski direk sačuvaj,\ndobru i zlu ima kraj,\nLa ilahe illallah.\n\nAllah jedan On je Hakk.\nTo priznati mora svak,\nod zuluma On je pak,\nLa ilahe illallah.\n\nO muslime, ne spavaj,\nuči Kur'an i slušaj,\nsvog sabaha ne puštaj,\nLa ilahe illallah.\n\nKada dođe Zadnji čas,\nuzalud je tražit spas.\nNek sačuva Allah nas,\nLa ilahe illallah."),
    ],
  },
  {
    topic_key: "topic_2",
    title: "Ponavljanje gradiva — Imanski šarti",
    sort_order: 22,
    blocks: [
      bnH("Ponavljanje je majka znanja", 2),
      bnP("Provjerite svoje znanje o imanskim šartima:"),
      bnNum("Koliko ima šartova — uvjeta u islamu?"),
      bnNum("Kako glasi prvi imanski šart?"),
      bnNum("Šta znači Amentu billahi?"),
      bnNum("Šta znači Ve rusulihi?"),
      bnNum("Prouči suru Ihlas!"),
      bnNum("Koji su najpoznatiji meleki?"),
      bnNum("Kako se zove melek koji je dostavljao Božije Objave?"),
      bnNum("Šta rade meleki zvani Kiramen katibin?"),
      bnNum("Nabroj velike Božije Objave!"),
      bnNum("Koja Božija Objava je objavljena Isa, alejhis-selamu?"),
      bnNum("Šta znači alejhis-selam?"),
      bnNum("Koja je posljednja Božija Objava?"),
      bnNum("Koliko sura ima u Kur'anu?"),
      bnNum("Koliko je u Kur'anu imenom spomenuto Božijih poslanika?"),
      bnNum("Ko je prvi čovjek i prvi Božiji poslanik?"),
      bnNum("Koji je posljednji Božiji poslanik?"),
      bnNum("Kada je rođen Muhammed, a.s.?"),
      bnNum("U kojoj godini života je Muhammed, a.s., primio prvu Objavu?"),
      bnNum("Prouči kasidu Ahmede Muhammede!"),
      bnNum("Kada će biti Sudnji dan?"),
      bnNum("Šta je nagrada za vjernike na Ahiretu?"),
      bnNum("Prouči suru El-Kevser!"),
      bnNum("Ko određuje sudbinu ljudima?"),
    ],
  },

  // ── TOPIC 3 ──
  {
    topic_key: "topic_3",
    title: "Islamski šarti i Sura Felek",
    sort_order: 23,
    blocks: [
      bnH("Islamski šarti (Glavne islamske dužnosti)", 2),
      bnP("Islamski šarti su glavne islamske dužnosti. Naređeni su u Kur'anu kao stroga obaveza. Vjernik i vjernica, osim vjerovanja, dužni su izvršavati islamske dužnosti."),
      bnH("Glavnih islamskih dužnosti ima pet:", 3),
      bnNum("KELIME-I-ŠEHADET"),
      bnNum("NAMAZE KLANJATI"),
      bnNum("RAMAZAN POSTITI"),
      bnNum("ZEKAT DAVATI"),
      bnNum("HADŽ OBAVITI"),
      bnP("Oni koji izvršavaju glavne islamske dužnosti i druge Božije zapovijedi nadaju se Allahovoj, dželle šanuhu, nagradi."),
      bnH("Suretul-Felek", 2),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("KUL E'ŪZU BI RABBIL-FELEK,\nMIN ŠERRI MĀ HALEK,\nVE MIN ŠERRI GĀSIKIN IZĀ VEKAB,\nVE MIN ŠERRIN-NEFFĀSĀTI FIL-'UKAD,\nVE MIN ŠERRI HĀSIDIN IZĀ HASED."),
      bnH("Prijevod:", 3),
      bnP("Reci: „Utječem se Gospodaru svitanja\nod zla onoga što On stvara,\ni od zla mrkle noći kada razastre tmine,\ni od zla smutljivca kada smutnju sije,\ni od zla zavidljivca kada zavist ne krije!”"),
    ],
  },
  {
    topic_key: "topic_3",
    title: "Prvi islamski šart: Kelime-i-šehadet i Sura Nas",
    sort_order: 24,
    blocks: [
      bnH("Prvi islamski šart", 2),
      bnH("KELIME-I-ŠEHADET — OČITOVANJE PRIPADNOSTI ISLAMU", 3),
      bnP("Šehadet znači: srcem vjerovati i jezikom svjedočiti postojanje Jednog Boga, Stvoritelja i Vladara svih svjetova, Koji je preko Muhammeda, a.s., ukazao Svoju milost cijelom čovječanstvu."),
      bnH("Ponovimo kako glasi Kelime-i-šehadet:", 3),
      bnH("EŠHEDU EN LĀ ILĀHE ILLALLĀH, VE EŠHEDU ENNE MUHAMMEDEN 'ABDUHŪ VE RESŪLUHŪ.", 3),
      bnP("Vjerujem i svjedočim da nema božanstva osim Allaha, i vjerujem i svjedočim da je Muhammed Allahov rob i poslanik!"),
      bnP("Kelime-i-šehadetom iskazujemo i potvrđujemo svoju pripadnost islamu kroz pokornost i vjerovanje u Allaha, dž.š., i poslanstvo Muhammeda, a.s."),
      bnH("Suretun-Nas", 2),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("KUL E'ŪZU BI RABBIN-NĀS,\nMELIKIN-NĀS,\nILĀHIN-NĀS,\nMIN ŠERRIL-VESVĀSIL-HANNĀS,\nELLEZĪ JUVESVISU FĪ SUDŪRIN-NĀS,\nMINEL-DŽINNETI VEN-NĀS."),
      bnH("Prijevod:", 3),
      bnP("Reci: „Tražim zaštitu Gospodara ljudi,\nVladara ljudi, Boga ljudi,\nod zla šejtana — napasnika,\nkoji zle misli unosi u srca ljudi —\nod džina i od ljudi!”"),
    ],
  },
  {
    topic_key: "topic_3",
    title: "Drugi islamski šart: Propisane namaze klanjati",
    sort_order: 25,
    blocks: [
      bnH("Drugi islamski šart", 2),
      bnH("PROPISANE NAMAZE KLANJATI", 3),
      bnP("Namaz je stroga islamska dužnost naređena u Kur'anu i potvrđena praksom Muhammeda, a.s. Klanjanjem namaza iskazujemo pokornost i poštovanje Allahu, dž.š., na najuzvišeniji način."),
      bnImage("/lessons/prayers/00_daily_prayers.jpg", "Pet dnevnih namaza u toku dana: Sabah, Podne, Ikindija, Akšam i Jacija"),
      bnH("U toku jednog dana, klanjamo pet namaza:", 3),
      bnBullet("SABAH: Sabah se klanja prije izlaska sunca."),
      bnBullet("PODNE: Podne se klanja kada je sunce iza polovine neba."),
      bnBullet("IKINDIJA: Ikindija se klanja kada sunce krene ka zapadu."),
      bnBullet("AKŠAM: Akšam se klanja kada sunce zađe."),
      bnBullet("JACIJA: Jacija se klanja kad padne potpuni mrak."),
      bnH("Osim pet dnevnih namaza, klanjamo i sljedeće namaze:", 3),
      bnBullet("DŽUMA: Klanja se petkom u vrijeme podne namaza."),
      bnBullet("TERAVIJA: Klanja se tokom ramazana, u vrijeme jacije namaza."),
      bnBullet("BAJRAM: Klanja se prvi dan Bajrama, dva puta godišnje."),
      bnBullet("DŽENAZA: Klanja se umrlim muslimanima i muslimankama."),
      bnH("Glavni položaji u namazu (Namaski ruknovi):", 3),
      bnImage("/lessons/prayers/01_takbir.jpg", "1. Iftitahi-tekbir: Donošenje tekbira uz dizanje ruku u visini ušiju i izgovaranje »Allāhu ekber«"),
      bnP("1. Iftitahi-tekbir: Namaz počinjemo izgovaranjem riječi »Allāhu ekber« (Allah je najveći), podižući ruke tako da palčevi dodiruju mehkote ušiju."),
      bnImage("/lessons/prayers/02_qiyam.jpg", "2. Kijam: Mirno stajanje u namazu s vezanim rukama"),
      bnP("2. Kijam: Stojimo mirno i skrušeno na sedžadi, s pogledom usmjerenim na mjesto sedžde. Desnu ruku stavljamo preko lijeve preko prsa ili pupka, te učimo Subhaneke, Fatihu i suru."),
      bnImage("/lessons/prayers/03_ruku.jpg", "3. Ruku': Pregibanje u namazu s pravim leđima i rukama na koljenima"),
      bnP("3. Ruku': Pregibamo se u pojasu tako da leđa budu ravna, obuhvatimo koljena dlanovima i tri puta izgovorimo »Subhāne Rabbijel-'azīm«."),
      bnImage("/lessons/prayers/04_itidal.jpg", "4. I'tidal: Uspravljanje nakon ruku'a"),
      bnP("4. I'tidal: Vraćamo se s pregiba u uspravan položaj govoreći »Semiallāhu limen hamideh«, a zatim »Rabbena lekel-hamd«."),
      bnImage("/lessons/prayers/05_sajdah.jpg", "5. Sedžda: Spuštanje lica na tlo pred Uzvišenim Allahom"),
      bnP("5. Sedžda: Spuštamo se na koljena, dlanove, čelo i nos na sedžadu u znak najveće pokornosti Allahu, dž.š., i tri puta izgovorimo »Subhāne Rabbijel-e'alā«. Činimo po dvije sedžde na svakom rekijatu."),
      bnImage("/lessons/prayers/06_tashahhud.jpg", "6. Ka'de-i ehire: Sjedenje u namazu i učenje Et-Tehijata"),
      bnP("6. Ka'de-i ehire: Sjedimo smireno na nogama, učimo Et-Tehijjatu, Salavate i Dove, te podižemo kažiprst pri izgovaranju Kelime-i-šehadeta."),
      bnP("Klanjati učimo kad pođemo u školu, a dužni smo redovno klanjati od desete godine života."),
    ],
  },
  {
    topic_key: "topic_3",
    title: "Treći islamski šart: Postiti mjesec ramazan",
    sort_order: 26,
    blocks: [
      bnH("Treći islamski šart", 2),
      bnH("POSTITI MJESEC RAMAZAN", 3),
      bnP("Post je islamska dužnost naređena Kur'anom. Ramazanski post je čuvanje od jela, pića, drugih tjelesnih uživanja i ružnih djela od zore do zalaska sunca."),
      bnP("Ramazan je najodabraniji mjesec u godini u kome je počela objava Kur'ana. U ramazanu postimo, dajemo zekat i sadekatul-fitr, klanjamo teraviju, spremamo iftare, učimo Kur'an i radimo druga dobra djela."),
      bnH("Post počinjemo nijetom:", 3),
      bnH("NEVEJTU EN ESŪME GADEN LILLĀHI TE'ĀLA FERĪDATEN MIN ŠEHRI RAMADĀNE.", 3),
      bnP("Prijevod: „Odlučih, u ime Allaha, da postim ovaj dan mjeseca ramazana!”"),
      bnH("Post prekidamo iftarom prije kojeg učimo dovu:", 3),
      bnH("ALLĀHUMME INNĪ LEKE SUMTU, VE BIKE ĀMENTU, VE 'ALEJKE TEVEKKELTU VE 'ALĀ RIZKIKE EFTARTU.", 3),
      bnP("Prijevod: „Allahu moj, radi Tebe postim, u Tebe vjerujem, u Tebe se uzdam, i Tvojom opskrbom se iftarim!”"),
      bnP("Postom su zaduženi svi odrasli, pametni i zdravi muslimani i muslimanke. Ramazanski post završava se svečanim danima Ramazanskog bajrama."),
    ],
  },
  {
    topic_key: "topic_3",
    title: "Četvrti islamski šart: Zekat davati i Sura Leheb",
    sort_order: 27,
    blocks: [
      bnH("Četvrti islamski šart", 2),
      bnH("ZEKAT DAVATI", 3),
      bnP("Zekat je stroga islamska dužnost propisana Kur'anom svim imućnim muslimanima, da obavezno izdvoje i daju jedan dio imovine iz viška imetka, islamskim odgojno-obrazovnim ustanovama i siromašnim muslimanima."),
      bnP("Davalac zekata postiže Božije zadovoljstvo i milost, čisti imetak od tuđeg prava, štiti ga od propadanja i čuva svoje srce od škrtosti. Zekat se obično daje uz ramazan, a može se dati i tokom cijele godine."),
      bnH("Imovina na koju treba dati zekat:", 3),
      bnBullet("Poljoprivredni proizvodi"),
      bnBullet("Zlato, srebro i novac"),
      bnBullet("Trgovačka roba"),
      bnBullet("Stoka"),
      bnP("Pravo i dužnost da sakuplja zekat isključivo pripada Islamskoj zajednici."),
      bnH("Suretul-Leheb", 2),
      bnH("BISMILLĀHIR-RAHMĀNIR-RAHĪM", 3),
      bnP("TEBBET JEDĀ EBĪ LEHEBIN VE TEBB,\nMĀ AGNĀ 'ANHU MĀLUHŪ VE MĀ KESEB,\nSE JASLĀ NĀREN ZĀTE LEHEB,\nVEMRE-'ETUHŪ HAMMĀLETEL-HATAB,\nFĪ DŽĪDIHĀ HABLUN MIN MESED."),
      bnH("Prijevod:", 3),
      bnP("Neka propadne Ebu Leheb, i propao je!\nNeće mu biti od koristi blago njegovo,\na ni ono što je stekao.\nUći će on, sigurno, u vatru rasplamsalu,\ni žena njegova koja spletkari;\no vratu njenu bit će uže od ličine usukane!"),
    ],
  },
  {
    topic_key: "topic_3",
    title: "Peti islamski šart: Hadž obaviti i Telbija",
    sort_order: 28,
    blocks: [
      bnH("Peti islamski šart", 2),
      bnH("HADŽ OBAVITI", 3),
      bnP("Hadž je peta islamska dužnost i Božija naredba svakom punoljetnom, pametnom, imućnom i zdravom muslimanu i muslimanki da ga obavi jednom u životu kad bude u mogućnosti. Hadž je posjeta Kabi i drugim svetim mjestima u Mekki."),
      bnP("Prije odlaska na hadž, dužnost hadžije je da izmiri dugove ako ih ima i obezbjedi porodicu dok se ne vrati."),
      bnH("Kraj Kabe sam ja stajao", 3),
      bnP("Kraj Kabe sam ja stajao,\nhej, aman, aman, ja stajao,\ncrne grijehe sapirao,\nhej, aman, aman, sapirao!\n\nSvom se Rabbu odzivao:\nLebbejkellāhumme, lebbejk,\nlebbejkallāhu!\nlebbejkellāhumme, lebbejk,\nlebbejkellāh!\n\nU tavafu hodao sam,\nhej, aman, aman, hodao sam,\nka'no zvijezda drhtao sam,\nhej, aman, aman, drhtao sam.\n\nKo Ibrahim vikao sam:\nLebbejkellāhumme, lebbejk,\nlebbejkallāhu!\nlebbejkellāhumme, lebbejk,\nlebbejkellāh!\n\nPokraj vrela Zemzemova\nhej, aman, aman, zemzemova,\nslegla jata labudova,\nhej, aman, aman, labudova!\n\nŽamor želja i glasova:\nLebbejkellāhumme, lebbejk,\nlebbejkallāhu!\nlebbejkellāhumme, lebbejk,\nlebbejkellāh!\n\nIz srdašca ašikane,\nhej, aman, aman, ašikane,\nte rijeke neprestane,\nhej, aman, aman, neprestane!\n\nTeče islam na sve strane:\nLebbejkellāhumme, lebbejk,\nlebbejkallāhu!\nlebbejkellāhumme, lebbejk,\nlebbejkellāh!"),
    ],
  },
  {
    topic_key: "topic_3",
    title: "Ponavljanje gradiva — Islamski šarti",
    sort_order: 29,
    blocks: [
      bnH("Ponavljanje je majka znanja", 2),
      bnP("Provjerite svoje znanje o islamskim dužnostima:"),
      bnNum("Koliko ima glavnih islamskih dužnosti?"),
      bnNum("Kako glasi prvi islamski šart?"),
      bnNum("Šta svjedočimo Kelime-i-šehadetom?"),
      bnNum("Koji je drugi islamski šart?"),
      bnNum("Koliko ima dnevnih namaza?"),
      bnNum("Kada klanjamo sabah-namaz?"),
      bnNum("U koje vrijeme se klanja džuma-namaz?"),
      bnNum("Kako glasi treći islamski šart?"),
      bnNum("Kako glasi nijet za post?"),
      bnNum("Prouči dovu uz koju se iftarimo."),
      bnNum("Od čega se čuvamo prilikom posta?"),
      bnNum("Ko je dužan postiti?"),
      bnNum("Koji je četvrti islamski šart?"),
      bnNum("Na koju imovinu trebamo dati zekat?"),
      bnNum("Šta je to hadž?"),
      bnNum("Ko je dužan obaviti hadž?"),
      bnNum("Prouči suru Felek."),
      bnNum("Kako glasi Suretun-Nas?"),
      bnNum("Prouči suru Leheb."),
    ],
  },
];

export interface GermanLessonItem {
  topic_key?: string;
  bosnianTitle: string;
  germanTitle: string;
  sortOrder: number;
  blocks: BlockItem[];
}

export const GERMAN_LESSONS: GermanLessonItem[] = [
  // TOPIC 1
  {
    bosnianTitle: "E'uzubila i Bismila",
    germanTitle: "E'ūzubillāh und Bismillāh",
    sortOrder: 1,
    blocks: [
      { type: "h", level: 2, text: "E'ūzubillāh" },
      { type: "p", text: "Die ersten Worte, die wir lernen, lauten:" },
      { type: "h", level: 3, text: "E'ŪZUBILLĀHI MINEŠ-ŠEJTĀNIR-RADŽĪM" },
      { type: "p", text: "Diese Worte bedeuten: „Ich nehme Zuflucht bei Allah vor dem verfluchten Schaytan (Teufel).”" },
      { type: "p", text: "Wir sprechen diese Worte:" },
      { type: "b", text: "damit wir in Sicherheit und geschützt sind" },
      { type: "b", text: "damit wir leicht und gut lernen" },
      { type: "b", text: "damit wir fröhlich und sicher spielen" },
      { type: "b", text: "damit wir ruhig schlafen und schöne Träume haben" },
      { type: "h", level: 2, text: "Bismillāh" },
      { type: "p", text: "Mit welchen Worten beginnen wir jede gute Tat? Es sind die Worte, die jeder Muslim und jede Muslima kennen sollte:" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "Lernen wir die Bedeutung dieser Worte: „Im Namen Allahs, des Allerbarmers, des Barmherzigen!”" },
      { type: "h", level: 2, text: "Wann sprechen wir E'ūzubillāh und Bismillāh?" },
      { type: "b", text: "Wenn wir essen und trinken" },
      { type: "b", text: "Wenn wir lernen und lesen" },
      { type: "b", text: "Wenn wir Fahrrad fahren" },
      { type: "b", text: "Wenn wir ins Auto einsteigen" },
      { type: "b", text: "Wenn wir das Haus betreten" },
      { type: "b", text: "Wenn wir schlafen gehen" },
      { type: "b", text: "Vor dem Spielen" },
      { type: "b", text: "Wenn wir unsere Kleidung anziehen" },
      { type: "p", text: "Darüber hinaus sprechen wir E'ūzubillāh und Bismillāh in vielen weiteren Lebenslagen. Frage deinen Muallim (Lehrer), wann man sie noch spricht." },
    ],
  },
  {
    bosnianTitle: "Čovjek je najljepše Allahovo stvorenje",
    germanTitle: "Der Mensch ist Allahs schönste Schöpfung",
    sortOrder: 2,
    blocks: [
      { type: "h", level: 2, text: "Der Mensch ist Allahs schönste Schöpfung" },
      { type: "p", text: "Allah, der Erhabene, hat die gesamte Welt erschaffen:" },
      { type: "b", text: "Den Menschen" },
      { type: "b", text: "Die Pflanzen" },
      { type: "b", text: "Die Tiere" },
      { type: "b", text: "Die Erde" },
      { type: "b", text: "Den Himmel" },
      { type: "b", text: "Das Weltall" },
      { type: "p", text: "Im Heiligen Koran spricht Allah der Erhabene:" },
      { type: "h", level: 3, text: "„Wahrlich, Wir haben den Menschen in schönster Gestalt erschaffen.”" },
      { type: "p", text: "(Koran, Sure At-Tin, Vers 4)" },
    ],
  },
  {
    bosnianTitle: "Ja u mekteb idem i dove za početak",
    germanTitle: "Ich gehe in die Mekteb & Bittgebete zum Anfang",
    sortOrder: 3,
    blocks: [
      { type: "h", level: 2, text: "Ich gehe in die Mekteb" },
      { type: "p", text: "Die Mekteb ist eine kleine Schule bei oder in der Moschee. In der Mekteb spielen wir und lernen:" },
      { type: "b", text: "über den islamischen Glauben" },
      { type: "b", text: "über die islamischen Pflichten" },
      { type: "b", text: "über das islamische Verhalten und Benehmen" },
      { type: "h", level: 3, text: "Was wir in die Mekteb mitbringen:" },
      { type: "b", text: "Ilmihal (Lehrbuch)" },
      { type: "b", text: "Heft" },
      { type: "b", text: "Bleistift" },
      { type: "b", text: "Radiergummi" },
      { type: "b", text: "Rucksack / Schultasche" },
      { type: "h", level: 2, text: "Bittgebete für einen gesegneten Anfang" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "h", level: 3, text: "RABBI JESSIR VE LĀ TUASSIR, RABBI TEMMIM BIL-HAJR. ĀMĪN." },
      { type: "p", text: "O mein Herr, schenke Erleichterung und erschwere nicht. O mein Herr, vollende es mit dem Guten. Amin!" },
      { type: "h", level: 3, text: "RABBI ZIDNĪ ILMĀ" },
      { type: "p", text: "Mein Herr, vermehre mein Wissen!" },
      { type: "h", level: 3, text: "Gedicht: Mirza eilt zum Unterricht" },
      { type: "p", text: "Ein glücklicher Tag ist erwacht,\nMirza geht freudig und lacht.\nEr hüpft vergnügt – jeder kann es seh'n,\nzur Mekteb sieht man Mirza geh'n.\n\nIn seiner Hand die kleine Tasche,\ndarin das Heft und die Mappe,\nund das Lehrbuch Ilmihal,\nsein erstes Wort: Bismillāh.\n\n(R. Kadić)" },
    ],
  },
  {
    bosnianTitle: "Vjera islam i Kelime-i-šehadet",
    germanTitle: "Die Religion Islam und das Glaubensbekenntnis (Shahada)",
    sortOrder: 4,
    blocks: [
      { type: "h", level: 2, text: "Die Religion Islam" },
      { type: "p", text: "Unsere Religion heißt Islam." },
      { type: "h", level: 3, text: "Was ist der Islam?" },
      { type: "p", text: "Der Islam ist die Religion, die Allah, der Erhabene, durch Seinen Gesandten Muhammad, Friede sei mit ihm, der gesamten Menschheit offenbart hat." },
      { type: "h", level: 3, text: "Was bedeutet Islam?" },
      { type: "p", text: "Islam bedeutet Ergebung und Hingabe an Allah, den Erhabenen." },
      { type: "h", level: 3, text: "Worin besteht die Hingabe an Allah?" },
      { type: "p", text: "Muslime glauben an Allah, erfüllen die religiösen Pflichten und Gebote und tun das Gute. Sie verhalten sich vorbildlich, sprechen die Wahrheit und helfen ihren Mitmenschen." },
      { type: "p", text: "„Der Islam ist wie das Sonnenlicht,\nwenn er einmal dein Herz berührt,\nliebst du die ganze Welt,\nund Hass in dir verfällt.”\n(R. Kadić)" },
      { type: "h", level: 2, text: "Kalima ash-Shahada (Das Glaubensbekenntnis)" },
      { type: "p", text: "Mit der Shahada bezeugen wir, dass wir Muslime sind." },
      { type: "h", level: 3, text: "Wie lautet das Glaubensbekenntnis?" },
      { type: "h", level: 3, text: "EŠHEDU EN LĀ ILĀHE ILLALLĀH, VE EŠHEDU ENNE MUHAMMEDEN 'ABDUHŪ VE RESŪLUHŪ." },
      { type: "p", text: "Übersetzung: „Ich bezeuge, dass es keinen Gott gibt außer Allah, und ich bezeuge, dass Muhammad Sein Diener und Gesandter ist!”" },
    ],
  },
  {
    bosnianTitle: "Selam — Islamski pozdrav",
    germanTitle: "Salam — Der islamische Friedensgruß",
    sortOrder: 5,
    blocks: [
      { type: "h", level: 2, text: "Salam — Der islamische Friedensgruß" },
      { type: "p", text: "Der Salam ist der gegenseitige Gruß der Muslime." },
      { type: "h", level: 3, text: "Wie grüßt und erwidert man den Salam?" },
      { type: "p", text: "Gruß: As-salāmu 'alejkum!\nAntwort: Ve 'alejkumus-selām!" },
      { type: "p", text: "Bedeutung: Friede und Heil sei mit euch!" },
      { type: "p", text: "„As-salāmu 'alejkum erschallt von allen Seiten,\nSalam, Friedensgruß möge uns stets begleiten.”" },
      { type: "h", level: 3, text: "Wann und wem entbieten wir den Salam?" },
      { type: "b", text: "Beim Betreten und Verlassen des Hauses" },
      { type: "b", text: "Wenn wir Muslime auf der Straße treffen" },
      { type: "b", text: "Jüngere grüßen ältere Personen zuerst" },
      { type: "b", text: "Männer entbieten zuerst den Gruß" },
      { type: "b", text: "Beim Hinzukommen zu einer Gruppe oder beim Verabschieden" },
      { type: "p", text: "Übe mit deinem Muallim spielerisch den Friedensgruß in verschiedenen Alltagssituationen!" },
    ],
  },
  {
    bosnianTitle: "Čistoća u islamu",
    germanTitle: "Reinheit und Hygiene im Islam",
    sortOrder: 6,
    blocks: [
      { type: "h", level: 2, text: "Reinheit (Taharah)" },
      { type: "p", text: "Reinheit ist die halbe Gesundheit. Deshalb achten wir stets auf die Hygiene unseres Körpers und unserer Kleidung." },
      { type: "p", text: "Wasser ist eine große Gabe Allahs an die Menschen, die wir zum Trinken, Kochen, Waschen des Körpers und der Kleidung nutzen." },
      { type: "p", text: "Allah liebt Ordnung und Reinlichkeit, und Muslime sollten stets sauber und gepflegt sein." },
      { type: "p", text: "Der Prophet Muhammad, Friede sei mit ihm, sagte: „Die Reinheit ist ein Teil des Glaubens.”" },
      { type: "h", level: 3, text: "Zur persönlichen Hygiene gehört:" },
      { type: "b", text: "Händewaschen vor und nach dem Essen" },
      { type: "b", text: "Regelmäßiges Baden und Duschen" },
      { type: "b", text: "Regelmäßiges Zähneputzen" },
      { type: "b", text: "Regelmäßiges Schneiden der Fingernägel" },
    ],
  },
  {
    bosnianTitle: "Voda je Allahov dar",
    germanTitle: "Das Wasser ist eine Gabe Allahs",
    sortOrder: 7,
    blocks: [
      { type: "h", level: 2, text: "Das Wasser ist eine Gabe Allahs" },
      { type: "p", text: "Ein gewöhnlicher Sommertag. Sejid spielte mit anderen Kindern im Hof der Moschee. Er unterbrach das Spiel und rannte ins Haus:" },
      { type: "p", text: "„Mutter, ich habe Durst, kann ich ein Glas Wasser bekommen?”" },
      { type: "p", text: "Nachdem er getrunken und gedankt hatte, fragte er:" },
      { type: "p", text: "„Schenkt uns Allah auch das Wasser? Wie herrlich es ist, wenn der Durst gestillt ist. So fühlen sich doch sicher alle?”" },
      { type: "p", text: "„Ja, Sejid. Damit der Mensch seine Bedürfnisse stillen kann, schenkt Allah ihm das Wasser, welches der Ursprung allen Lebens ist.”" },
      { type: "p", text: "„Gibt Er auch meinem Kätzchen Wasser?”, fragte er. Die Mutter nickte bejahend." },
      { type: "p", text: "„Und den Vögeln, Hasen, Lämmern und anderen Tieren?”" },
      { type: "p", text: "„Ja, Sejid. Allah, dž.š., je svim stvorenjima darovao vodu da bi ugasili žeđ i zadovoljili druge potrebe: i biljkama, i drveću, i svemu što je živo. Svemu što zavisi od nje, On daje vodu.”" },
      { type: "p", text: "„Regnet es deshalb?”, fragte Sejid — „Weil wenn es regnet, kann ich zwar nicht draußen spielen, aber jetzt weiß ich, dass sich die Erde und die Pflanzen über den Regen freuen.”" },
      { type: "p", text: "Die Mutter streichelte ihm über den Kopf und sagte:" },
      { type: "p", text: "„Ja, mein Sohn, du hast recht, sie lieben den Regen. Schau in den Himmel: Siehst du die dichten Wolken? Sie bringen den Regen. Schau, schon fallen die ersten Tropfen. Hilfst du mir, die Fenster zu schließen?”" },
      { type: "p", text: "Der Junge half fröhlich und sagte:" },
      { type: "p", text: "„Mutter, der Regen wird lange fallen und alle Pflanzen trinken. Und was geschieht mit dem Wasser auf der Erde?”" },
      { type: "p", text: "„Ein Teil sammelt sich in Quellen. Von dort wird das saubere Wasser in die Wasserleitungen geführt, die es in unsere Häuser bringen.”" },
      { type: "p", text: "Da rief Sejid:" },
      { type: "p", text: "„Ohne Wasser könnte ich mich gar nicht waschen! Mutter, wie wichtig das Wasser für alle ist! Allah, unser Herr, ist wahrhaft großzügig, dass Er uns Wasser schenkt!”" },
      { type: "p", text: "Wasser ist eine wunderbare Gabe Allahs!" },
    ],
  },
  {
    bosnianTitle: "Desna strana u islamu",
    germanTitle: "Der Vorzug der rechten Seite im Islam",
    sortOrder: 8,
    blocks: [
      { type: "h", level: 2, text: "Die rechte Seite" },
      { type: "p", text: "Der Islam gibt der rechten Seite den Vorzug. Deshalb verrichten wir alle schönen und guten Dinge mit der rechten Hand und dem rechten Fuß:" },
      { type: "b", text: "Mit der rechten Hand essen und trinken" },
      { type: "b", text: "Zuerst den rechten Ärmel anziehen" },
      { type: "b", text: "Zuerst den rechten Schuh anziehen" },
      { type: "b", text: "Auf der rechten Seite schlafen" },
      { type: "b", text: "Mit dem rechten Fuß ins Haus und in die Moschee eintreten" },
      { type: "b", text: "Mit dem linken Fuß aus dem Haus hinaustreten" },
    ],
  },
  {
    bosnianTitle: "Hrana i piće — Halal i haram",
    germanTitle: "Essen und Trinken — Halal und Haram",
    sortOrder: 9,
    blocks: [
      { type: "h", level: 2, text: "Essen und Trinken" },
      { type: "p", text: "Allah, der Erhabene, hat den Menschen erschaffen und ihm Nahrung geschenkt. Er hat ihm alle guten, reinen Speisen und Getränke erlaubt (Halal) und schädliche Dinge verboten (Haram)." },
      { type: "h", level: 3, text: "Was HALAL (erlaubt) ist:" },
      { type: "b", text: "Hase, Schaf, Rind, Huhn, Fisch" },
      { type: "b", text: "Obst, Gemüse, Getreide und Milchprodukte" },
      { type: "h", level: 3, text: "Was HARAM (verboten) ist:" },
      { type: "b", text: "Schweinefleisch und Schweineerzeugnisse" },
      { type: "b", text: "Hund, Raubvögel, Frösche und Fleisch von Raubtieren" },
      { type: "b", text: "Alkohol und berauschende Getränke" },
      { type: "h", level: 3, text: "Verhaltensregeln beim Essen und Trinken:" },
      { type: "b", text: "Vor und nach dem Essen die Hände waschen" },
      { type: "b", text: "Vor dem Essen Bismillāh sagen und mit der rechten Hand essen" },
      { type: "b", text: "Keine zu heißen Speisen essen" },
      { type: "b", text: "Gemeinsam mit der Familie speisen" },
      { type: "b", text: "Nach dem Essen Allah mit „Al-hamdu lillāh” danken" },
      { type: "b", text: "Nach der Mahlzeit den Tisch abräumen" },
      { type: "b", text: "Nach dem Essen die Zähne putzen" },
    ],
  },
  {
    bosnianTitle: "Subhaneke i zahvalnost Allahu",
    germanTitle: "Subhanaka-Gebet und Dankbarkeit gegenüber Allah",
    sortOrder: 10,
    blocks: [
      { type: "h", level: 2, text: "Das Subhanaka-Gebet" },
      { type: "p", text: "Wir lobpreisen und danken Allah mit dem Subhanaka-Bittgebet:" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "h", level: 3, text: "SUBHĀNEKE ALLĀHUMME VE BI HAMDIKE, VE TEBĀREKESMUKE, VE TE'ĀLĀ DŽEDDUKE, VE LĀ ILĀHE GAJRUKE." },
      { type: "p", text: "Übersetzung: „Gepriesen seist Du, o Allah, und Dein ist das Lob, gesegnet ist Dein Name, erhaben ist Deine Majestät, und es gibt keinen Gott außer Dir.”" },
      { type: "h", level: 2, text: "Wir sollten Allah stets dankbar sein" },
      { type: "p", text: "Sejid machte mit seinem Vater einen Spaziergang. Als sie zurückkamen, rannte er ins Haus und umarmte seine Mutter:" },
      { type: "p", text: "„Mutter, was ich alles gesehen habe: kleine Vögel, Kätzchen, Küken und so vieles mehr!”" },
      { type: "p", text: "„Mein Sohn, ich freue mich, dass es dir so gefallen hat.”" },
      { type: "p", text: "„Ich hatte noch nie so viel Freude.”" },
      { type: "p", text: "„Dein Gesicht strahlt vor Glück”, sagte die Mutter." },
      { type: "p", text: "Der Junge setzte sich neben sie: „Mutter, welch eine schöne Welt Allah uns geschenkt hat!”" },
      { type: "p", text: "„Ja, mein Sohn, Allah hat wahrhaftig eine wunderschöne Welt erschaffen.”" },
      { type: "p", text: "„Dann müssen wir auch zu jenen gehören, die auf dem rechten Weg sind, und so unsere Dankbarkeit zeigen!”" },
      { type: "p", text: "„Sejid, ich stimme dir vollkommen zu. Wir sind beauftragt, diese Schönheit zu bewahren, die Allah uns anvertraut hat. Durch unsere guten Taten müssen wir zeigen, dass wir gute Diener unseres Schöpfers sind.”" },
      { type: "p", text: "„Wenn ihr dankbar seid, so werde Ich euch gewiss noch mehr geben; seid ihr aber undankbar, so ist Meine Strafe wahrlich streng.” (Koran, Sure Ibrahim, Vers 7)" },
    ],
  },
  {
    topic_key: "topic_1",
    bosnianTitle: "Sura El-Fatiha",
    germanTitle: "Sure Al-Fatiha (Die Eröffnende)",
    sortOrder: 11,
    blocks: [
      { type: "h", level: 2, text: "Sure Al-Fatiha" },
      { type: "p", text: "Al-Fatiha ist die erste Sure im Heiligen Koran." },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "EL-HAMDU LILLĀHI RABBIL-'ĀLEMĪN.\nER-RAHMĀNIR-RAHĪM.\nMĀLIKI JEVMID-DĪN.\nIJJĀKE N'ABUDU VE IJJĀKE NESTE'ĪN.\nIHDINES-SIRĀTAL-MUSTEKĪM.\nSIRĀTALLEZĪNE EN'AMTE 'ALEJHIM,\nGAJRIL-MAGDŪBI 'ALEJHIM VE LED-DĀLLĪN. ĀMĪN!" },
      { type: "h", level: 3, text: "Bedeutung:" },
      { type: "p", text: "Alles Lob gebührt Allah, dem Herrn der Welten,\ndem Allerbarmer, dem Barmherzigen,\ndem Herrscher am Tage des Gerichts.\nDir allein dienen wir, und Dich allein bitten wir um Hilfe.\nFühre uns den geraden Weg,\nden Weg derer, denen Du Gnade erwiesen hast,\nnicht derer, die Deinen Zorn erregt haben, und nicht der Irregehenden. Amin!" },
      { type: "p", text: "„Al-Fatiha ist die erste Sure des Korans,\nsie nährt die Seele des gläubigen Muslims,\njeder Gläubige möge diese Sure lernen\nund sich Allahs Rechtleitung zuwenden.”" },
    ],
  },
  {
    topic_key: "topic_1",
    bosnianTitle: "Ponavljanje gradiva — Uvodni dio",
    germanTitle: "Wiederholung — Einführungsteil",
    sortOrder: 12,
    blocks: [
      { type: "h", level: 2, text: "Wiederholung ist die Mutter des Wissens" },
      { type: "p", text: "Bisher haben wir gelernt: E'ūzubillāh, Bismillāh, Rabbi yassir, Shahada, Subhanaka und Al-Fatiha. Überprüfe dein Wissen:" },
      { type: "num", text: "Rezitierte E'ūzubillāh!" },
      { type: "num", text: "Rezitierte Bismillāh!" },
      { type: "num", text: "Womit beginnen wir jede gute Handlung?" },
      { type: "num", text: "Wer ist Allahs schönste Schöpfung?" },
      { type: "num", text: "Was lernen wir in der Mekteb?" },
      { type: "num", text: "Rezitierte das Bittgebet Rabbi yassir!" },
      { type: "num", text: "Wie heißt unsere Religion?" },
      { type: "num", text: "Was bedeutet Islam?" },
      { type: "num", text: "Womit bezeugen wir unsere Zugehörigkeit zum Islam?" },
      { type: "num", text: "Wie lautet das Glaubensbekenntnis (Kalima ash-Shahada)?" },
      { type: "num", text: "Wie heißt der islamische Friedensgruß?" },
      { type: "num", text: "Wie grüßt man und wie erwidert man den Friedensgruß?" },
      { type: "num", text: "Wem gebührt unser Dank?" },
      { type: "num", text: "Wie danken wir Allah, dem Erhabenen?" },
      { type: "num", text: "Wie lautet die erste Sure im Koran?" },
    ],
  },

  // ── TOPIC 2 ──
  {
    topic_key: "topic_2",
    bosnianTitle: "Pregled 33 šarta — Uvjeta u islamu",
    germanTitle: "Übersicht der 33 Pflichtbedingungen im Islam",
    sortOrder: 13,
    blocks: [
      { type: "h", level: 2, text: "Übersicht der 33 Pflichtbedingungen im Islam" },
      { type: "p", text: "Es gibt nur einen einzigen Gott. Er ist der Schöpfer und Erhalter aller Welten. Er hat den Menschen in bester Gestalt erschaffen und ihm den Verstand geschenkt. Der Verstand folgt der göttlichen Rechtleitung und fügt sich Seinem Willen." },
      { type: "p", text: "Das Fundament des Islam ist das Glaubensbekenntnis (Shahada). Es genügt jedoch nicht nur zu glauben, sondern die Pflichten müssen auch in die Tat umgesetzt werden." },
      { type: "h", level: 3, text: "Der Islam ruht auf 33 Bedingungen:" },
      { type: "h", level: 3, text: "Glaubensartikel (6 Iman-Bedingungen):" },
      { type: "num", text: "Āmantu billāhi (Ich glaube an Allah)" },
      { type: "num", text: "Wa malā'ikatihī (Ich glaube an Seine Engel)" },
      { type: "num", text: "Wa kutubihī (Ich glaube an Seine Bücher / Offenbarungen)" },
      { type: "num", text: "Wa rusulihī (Ich glaube an Seine Gesandten)" },
      { type: "num", text: "Wal-yawmil-ākhiri (Ich glaube an den Jüngsten Tag)" },
      { type: "num", text: "Wa bil-qadari khayrihī wa šarrihī minallāhi ta'ālā (Ich glaube an die göttliche Vorherbestimmung – dass alles Gute und Schwere durch Allahs Willen geschieht)" },
      { type: "h", level: 3, text: "Säulen des Islam (5 Pflichten):" },
      { type: "num", text: "Kalima ash-Shahada (Bezeugung des Glaubens)" },
      { type: "num", text: "Das tägliche Gebet (Salah) verrichten" },
      { type: "num", text: "Im Monat Ramadan fasten (Sawm)" },
      { type: "num", text: "Die Zakat-Abgabe entrichten" },
      { type: "num", text: "Die Pilgerfahrt (Hadsch) vollziehen" },
      { type: "h", level: 3, text: "Wudhu-Pflichten (4 Waschungsbedingungen):" },
      { type: "num", text: "Das Gesicht waschen" },
      { type: "num", text: "Beide Arme bis einschließlich der Ellbogen waschen" },
      { type: "num", text: "Über ein Viertel des Kopfes mit feuchten Händen streichen (Masah)" },
      { type: "num", text: "Beide Füße bis einschließlich der Knöchel waschen" },
      { type: "h", level: 3, text: "Ghusl-Pflichten (3 Ganzwaschungsbedingungen):" },
      { type: "num", text: "Den Mund gründlich ausspülen" },
      { type: "num", text: "Die Nase gründlich ausspülen" },
      { type: "num", text: "Den gesamten Körper vollständig waschen" },
      { type: "h", level: 3, text: "Tayammum-Bedingungen (2 Schritte der Trockenreinigung):" },
      { type: "num", text: "Die Absicht (Niyyah) fassen" },
      { type: "num", text: "Mit den Handflächen auf reine Erde schlagen und das Gesicht abstreichen; erneut aufschlagen und beide Arme bis zu den Ellbogen abstreichen" },
      { type: "h", level: 3, text: "Gebetsbedingungen vor dem Gebet (6 Voraussetzungen):" },
      { type: "num", text: "Reinheit des Körpers, der Kleidung und des Gebetsplatzes" },
      { type: "num", text: "Die rituelle Gebetswaschung (Wudhu) vollziehen" },
      { type: "num", text: "Vorschriftsmäßige Kleidung tragen (die Blöße bedecken)" },
      { type: "num", text: "Zur vorgeschriebenen Gebetszeit beten" },
      { type: "num", text: "Sich in Richtung der Qibla (Mekka) wenden" },
      { type: "num", text: "Die Absicht (Niyyah) für das jeweilige Gebet fassen" },
      { type: "h", level: 3, text: "Gebetssäulen während des Gebets (6 Pfeiler):" },
      { type: "num", text: "Iftitah-Takbir (Eröffnungs-Takbir: Allāhu Akbar)" },
      { type: "num", text: "Qiyam (Stehen im Gebet)" },
      { type: "num", text: "Qira'at (Rezitieren aus dem Koran)" },
      { type: "num", text: "Ruku' (Die Verbeugung)" },
      { type: "num", text: "Sadschda (Die Niederwerfung)" },
      { type: "num", text: "Qa'da Akhira (Das abschließende Sitzen im Gebet)" },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Imanski šarti — Islamsko vjerovanje",
    germanTitle: "Die Glaubensartikel (Iman) — Das islamische Glaubensbekenntnis",
    sortOrder: 14,
    blocks: [
      { type: "h", level: 2, text: "Die Glaubensartikel des Islam" },
      { type: "p", text: "Der islamische Glaube (Iman) besteht aus sechs grundlegenden Glaubensartikeln:" },
      { type: "num", text: "ĀMANTU BILLĀHI — Ich glaube an Allah" },
      { type: "num", text: "WA MALĀ'IKATIHĪ — Und ich glaube an Seine Engel" },
      { type: "num", text: "WA KUTUBIHĪ — Und ich glaube an Seine Bücher" },
      { type: "num", text: "WA RUSULIHĪ — Und ich glaube an Seine Gesandten" },
      { type: "num", text: "WAL-YAWMIL-ĀKHIRI — Und ich glaube an den Jüngsten Tag" },
      { type: "num", text: "WA BIL-QADARI KHAYRIHĪ WA ŠARRIHĪ MINALLĀHI TA'ĀLĀ — Und ich glaube an die Vorherbestimmung, dass alles Gute und Übel nach Allahs Willen und Bestimmung geschieht" },
      { type: "h", level: 3, text: "Verse über die Glaubensartikel" },
      { type: "p", text: "ĀMANTU BILLĀHI:\nIch glaube an den einen Gott,\nder jeden Diener erschaffen hat.\nEr schuf das gesamte Universum,\ndass es Ihn allein preist.\n\nWA MALĀ'IKATIHĪ:\nUnd ich glaube an alle Engel,\nohne Sünde und ohne Makel,\nso hat Gott sie erschaffen,\naus reinem Licht gewoben.\n\nWA KUTUBIHĪ:\nUnd ich glaube an die heiligen Bücher,\nes sind die Worte des Erhabenen.\nVier wurden auserwählt,\nim Koran bestätigt und bewahrt.\n\nWA RUSULIHĪ:\nUnd ich glaube an die Propheten,\nAllahs auserwählte Gesandte.\nSie brachten uns den Glauben,\nund lehrten uns jedes Gute.\n\nWAL-YAWMIL-ĀKHIRI:\nUnd ich glaube an den Jüngsten Tag,\nwenn die Taten auf der Waage wiegen.\nVor dem Feuer gilt es sich zu retten,\nund im Paradies Geborgenheit zu finden.\n\nWA BIL-QADARI KHAYRIHĪ WA ŠARRIHĪ MINALLĀHI TA'ĀLĀ:\nUnd ich glaube, dass alles was geschieht,\nwas stirbt und was geboren wird,\nwas die Nacht birgt und der Tag enthüllt,\ndurch Allahs Willen geschieht.\n\n(E. Nurović)" },
      { type: "p", text: "Jeder Muslim muss die Glaubensartikel kennen und von ganzem Herzen daran glauben." },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Prvi imanski šart: Āmentu billāhi i Sura Ihlas",
    germanTitle: "Der 1. Glaubensartikel: Glaube an Allah & Sure Al-Ikhlas",
    sortOrder: 15,
    blocks: [
      { type: "h", level: 2, text: "Der erste Glaubensartikel" },
      { type: "h", level: 3, text: "ĀMANTU BILLĀHI — ICH GLAUBE AN ALLAH, DEN ERHABENEN" },
      { type: "p", text: "Wenn wir über die Welt um uns herum nachdenken, führt uns der Verstand zu der Gewissheit, dass es einen vollkommenen, allmächtigen Schöpfer geben muss, der alles erschaffen hat und alles lenkt. Das ist Allah, der Erhabene. Allah ist der Schöpfer und Herr über alles, was wir sehen und was wir nicht sehen." },
      { type: "p", text: "Allah hat die Erde und den Himmel, die Pflanzen und die Tiere erschaffen. Und Er hat den Menschen in schönster Gestalt geschaffen." },
      { type: "p", text: "Wenn wir Seinen Namen aussprechen, fügen wir hinzu: jalla shanuhu (dž.š.) – Erhaben ist Seine Majestät." },
      { type: "h", level: 2, text: "Sure Al-Ikhlas (Die Aufrichtigkeit)" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "KUL HUVALLĀHU EHAD.\nALLĀHUS-SAMED.\nLEM JELID VE LEM JŪLED\nVE LEM JEKUN LEHŪ KUFUVEN EHAD." },
      { type: "h", level: 3, text: "Übersetzung:" },
      { type: "p", text: "Sprich: „Er ist Allah, ein Einziger.\nAllah, der Absolute (von dem alles abhängt).\nEr zeugt nicht und ist nicht gezeugt worden,\nund niemand ist Ihm ebenbürtig.”" },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Drugi imanski šart: Ve melāiketihī (Meleki)",
    germanTitle: "Der 2. Glaubensartikel: Glaube an die Engel (Mala'ika)",
    sortOrder: 16,
    blocks: [
      { type: "h", level: 2, text: "Der zweite Glaubensartikel" },
      { type: "h", level: 3, text: "WA MALĀ'IKATIHĪ — ICH GLAUBE AN ALLAHS ENGEL" },
      { type: "p", text: "Engel sind vernunftbegabte, geistige, unsichtbare Wesen. Sie wurden aus Licht (Nur) erschaffen. Engel sündigen nicht; sie preisen und verherrlichen Allah unablässig. Sie dienen Allah ständig und haben feste Aufgaben. Sie sind weder männlich noch weiblich, sie essen und trinken nicht. Es gibt unzählige Engel, deren genaue Zahl nur Allah kennt." },
      { type: "h", level: 3, text: "Die bekanntesten Engel und ihre Aufgaben:" },
      { type: "b", text: "DŽIBRIL (GABRIEL): Überbrachte den Propheten die göttlichen Offenbarungen" },
      { type: "b", text: "AZRAIL (TODESENGEL): Trennt im Augenblick des Todes die Seele vom Körper" },
      { type: "b", text: "MIKAIL (MICHAEL): Verwaltet die Naturerscheinungen (Wind, Regen, Pflanzenwachstum)" },
      { type: "b", text: "ISRAFIL (RAPHAEL): Wird mit dem Stoß ins Horn den Weltuntergang und die Auferstehung ankündigen" },
      { type: "b", text: "KIRAMEN KATIBIN: Prate ljude, pišu njihova djela i donose im dobre misli" },
      { type: "b", text: "MUNKIR I NEKIR: Ispituju u mezaru svakog čovjeka" },
      { type: "p", text: "Außer den Engeln hat Allah auch andere unsichtbare Wesen erschaffen: die Dschinn und die Schayatine (Teufel). Der Schaytan bringt schlechte Gedanken und verleitet zum Bösen." },
      { type: "p", text: "Zuflucht vor dem verfluchten Schaytan suchen wir bei Allah mit den Worten:" },
      { type: "h", level: 3, text: "E'ŪZUBILLĀHI MINEŠ-ŠEJTĀNIR-RADŽĪM" },
      { type: "p", text: "Ich nehme Zuflucht bei Allah vor dem verfluchten Schaytan." },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Treći imanski šart: Ve kutubihī (Božije knjige)",
    germanTitle: "Der 3. Glaubensartikel: Glaube an die göttlichen Bücher",
    sortOrder: 17,
    blocks: [
      { type: "h", level: 2, text: "Der dritte Glaubensartikel" },
      { type: "h", level: 3, text: "WA KUTUBIHĪ — ICH GLAUBE AN ALLAHS BÜCHER UND OFFENBARUNGEN" },
      { type: "p", text: "Allahs Bücher sind göttliche Offenbarungen, die der Engel Dschibril den Gesandten überbrachte, damit diese sie den Menschen verkünden und erklären. Die erste Offenbarung erging an den ersten Menschen, Adam (a.s.)." },
      { type: "p", text: "Alle Offenbarungen riefen die Menschen dazu auf, an den einen Gott zu glauben und Ihm zu dienen. Es wurden vier große Bücher sowie kleinere Schriftrollen (Suhuf) herabgesandt." },
      { type: "h", level: 3, text: "Die vier großen Offenbarungsbücher sind:" },
      { type: "b", text: "TEVRAT (THORA): Offenbart an Musa (Moses), Friede sei mit ihm" },
      { type: "b", text: "ZEBUR (PSALMEN): Offenbart an Davud (David), Friede sei mit ihm" },
      { type: "b", text: "INDŽIL (EVANGELIUM): Offenbart an Isa (Jesus), Friede sei mit ihm" },
      { type: "b", text: "KUR'AN (KORAN): Offenbart an Muhammed, Friede sei mit ihm" },
      { type: "h", level: 3, text: "Der Heilige Koran (Kur'an-i Kerim)" },
      { type: "p", text: "Der Koran ist das letzte Buch Allahs, das durch den Propheten Muhammad (a.s.) der gesamten Menschheit offenbart wurde. Er enthält Wegweisungen, Ratschläge, Gebete und Lebensregeln. Er wurde auf Arabisch über einen Zeitraum von 23 Jahren herabgesandt und besteht aus 114 Suren." },
      { type: "p", text: "„Es gibt kein besseres Buch als den Koran und keine schönere Religion als den Islam.\nIn ihm liegen weise Worte, die zu wahrem Glück führen.”" },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Četvrti imanski šart: Ve rusulihī (Božiji poslanici)",
    germanTitle: "Der 4. Glaubensartikel: Glaube an die Propheten und Gesandten",
    sortOrder: 18,
    blocks: [
      { type: "h", level: 2, text: "Der vierte Glaubensartikel" },
      { type: "h", level: 3, text: "WA RUSULIHĪ — ICH GLAUBE AN ALLAHS GESANDTE" },
      { type: "p", text: "Propheten sind auserwählte Menschen, die Allah aus Seiner Barmherzigkeit zu den Menschen sandte, um ihnen Seine Offenbarung und Rechtleitung zu überbringen. Allah sandte jedem Volk Gesandte. Im Koran werden 25 Propheten namentlich erwähnt." },
      { type: "p", text: "Der erste Mensch auf Erden war Adam (a.s.), der zugleich der erste Prophet war. Der letzte Prophet ist Muhammad (a.s.), nach dem bis zum Jüngsten Tag kein weiterer Prophet kommen wird." },
      { type: "h", level: 3, text: "Besonders herausragende Propheten sind:" },
      { type: "num", text: "Ādem / Adam (a.s.)" },
      { type: "num", text: "Nūh / Noah (a.s.)" },
      { type: "num", text: "Ibrāhīm / Abraham (a.s.)" },
      { type: "num", text: "Mūsā / Moses (a.s.)" },
      { type: "num", text: "Īsā / Jesus (a.s.)" },
      { type: "num", text: "Muhammed / Muhammad (a.s.)" },
      { type: "p", text: "Nach dem Namen eines Propheten sagen wir: 'alejhis-selām (a.s.) – Friede sei auf ihm." },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Muhammed, a.s. — Posljednji Božiji poslanik",
    germanTitle: "Muhammad (a.s.) — Der letzte Gesandte Allahs",
    sortOrder: 19,
    blocks: [
      { type: "h", level: 2, text: "Muhammad, Friede sei mit ihm" },
      { type: "p", text: "Muhammed (a.s.) ist der letzte Gesandte Allahs. Er wurde im Jahr 571 n. Chr. in Mekka im Stamm Quraisch geboren. Sein Vater hieß Abdullah und seine Mutter Amina. Veoma rano ostao je bez roditelja. Od šeste godine brigu o njemu preuzima njegov djed Abdulmuttalib, a potom amidža Ebu Talib." },
      { type: "p", text: "Allah hat ihn zu Seinem Gesandten erwählt. Im Alter von vierzig Jahren empfing er in der Höhle Hira die erste Offenbarung und wurde zum Propheten berufen. Nach dreizehn Jahren wanderte er mit den Muslimen von Mekka nach Medina aus (Hidschra). Er verstarb im Alter von 63 Jahren in Medina (Medinetun-Nebijj)." },
      { type: "p", text: "Muhammed (a.s.) ist das beste Vorbild für die Menschen, wie man wahrhaftig glaubt und lebt." },
      { type: "h", level: 3, text: "Kasida: Ahmede Muhammede" },
      { type: "p", text: "Mein Herz empfindet Sehnsucht,\ndass es nicht die Ehre hatte,\nan deiner Seite zu verweilen,\no Ahmed, o Muhammed.\n\nDu bist Barmherzigkeit des Erbarmers,\nFreude meines Herzens,\nHeilung für jede Wunde,\no Ahmed, o Muhammed.\n\nMein Herz brennt voller Liebe,\nsehnt sich danach dich zu erblicken,\nunser geliebter Prophet,\no Ahmed, o Muhammed.\n\nMeiner Seele ist es ein Labsal,\nwenn sie dir Segenswünsche sendet,\nwenn sie deinen Namen nennt,\no Ahmed, o Muhammed." },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Peti imanski šart: Vel-jevmil-āhiri i Sura Kevser",
    germanTitle: "Der 5. Glaubensartikel: Glaube an den Jüngsten Tag & Sure Al-Kawthar",
    sortOrder: 20,
    blocks: [
      { type: "h", level: 2, text: "Der fünfte Glaubensartikel" },
      { type: "h", level: 3, text: "WAL-JEVMIL-ĀHIRI — ICH GLAUBE AN DEN JÜNGSTEN TAG" },
      { type: "p", text: "Nach dem vergänglichen irdischen Leben werden alle Menschen für das ewige Jenseits (Ahirat) auferweckt. Am Jüngsten Tag werden alle Menschen über ihre Taten Rechenschaft ablegen." },
      { type: "p", text: "Jedem Menschen wird sein Buch der guten und schlechten Taten vorgelegt, das von den Engeln Kiramen Katibin verfasst wurde." },
      { type: "p", text: "Wer an Allah glaubte und Gutes tat, wird durch Seine Barmherzigkeit ins Paradies (Džennet) eingehen. Wann der Jüngste Tag eintrifft, weiß allein Allah." },
      { type: "h", level: 3, text: "Das Paradies (Džennet)" },
      { type: "p", text: "Das Paradies ist die ewige Wohnstätte im Jenseits, in der die Gläubigen in vollkommenem Glück und Frieden weilen." },
      { type: "h", level: 3, text: "Die Hölle (Džehennem)" },
      { type: "p", text: "Die Hölle ist die Stätte der Strafe im Jenseits für jene, die ungläubig und ungerecht waren, es sei denn, Allah erbarmt sich ihrer." },
      { type: "h", level: 2, text: "Sure Al-Kawthar (Die Fülle)" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "INNĀ E'ATAJNĀKEL-KEVSER,\nFE SALLI LI RABBIKE VEN-HAR,\nINNE ŠĀNI'EKE HUVEL-EBTER." },
      { type: "h", level: 3, text: "Übersetzung:" },
      { type: "p", text: "Wahrlich, Wir haben dir die Fülle (an Gutem) gegeben.\nSo bete zu deinem Herrn und opfere.\nGewiss, derjenige, der dich hasst, ist vom Guten abgeschnitten." },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Šesti imanski šart: Ve bil-kaderi (Kader) i pjesma",
    germanTitle: "Der 6. Glaubensartikel: Die göttliche Vorherbestimmung (Kader)",
    sortOrder: 21,
    blocks: [
      { type: "h", level: 2, text: "Der sechste Glaubensartikel" },
      { type: "h", level: 3, text: "VE BIL-KADERI HAJRIHĪ VE ŠERRIHĪ MINELLĀHI TE'ĀLA" },
      { type: "p", text: "Ich glaube, dass alles, was geschieht – Gutes wie Schweres –, nach Allahs Willen und göttlicher Vorherbestimmung geschieht." },
      { type: "p", text: "Allah ist der Schöpfer aller Dinge. Was Allah will, geschieht, und was Er nicht will, kann niemals geschehen." },
      { type: "p", text: "Allah hat dem Menschen Verstand und freien Willen verliehen, damit er sich für das Gute entscheidet. Im Unglück soll der Gläubige geduldig und standhaft bleiben. Allah weiß alles, was war, was ist und was sein wird." },
      { type: "h", level: 3, text: "Gedicht: Suche deinen Herrn" },
      { type: "p", text: "Allāh, Allāh, huve Rabbunā, Lā ilāhe illallāh.\n\nSuche deinen Herrn im Gebet,\nSein Gedenken dir Kraft verleiht,\nwirst immer stronger Tag für Tag,\nLā ilāhe illallāh.\n\nLass das Gebet niemals vergeh'n,\nden Pfeiler des Glaubens aufrecht steh'n,\nalles Gute und Schwere ein Ende hat,\nLā ilāhe illallāh.\n\nAllah ist Einer, Er ist die Wahrheit,\ndies bezeugt jeder in Klarheit,\nLā ilāhe illallāh.\n\nO Muslim, sei wachsam und rein,\nlies den Koran und präg ihn dir ein,\nversäume das Morgengebet nicht,\nLā ilāhe illallāh." },
    ],
  },
  {
    topic_key: "topic_2",
    bosnianTitle: "Ponavljanje gradiva — Imanski šarti",
    germanTitle: "Wiederholung — Die Glaubensartikel (Iman)",
    sortOrder: 22,
    blocks: [
      { type: "h", level: 2, text: "Wiederholung ist die Mutter des Wissens" },
      { type: "p", text: "Überprüfe dein Wissen über die Glaubensartikel:" },
      { type: "num", text: "Wie viele Pflichtbedingungen (Schurut) gibt es insgesamt im Islam?" },
      { type: "num", text: "Wie lautet der erste Glaubensartikel?" },
      { type: "num", text: "Was bedeutet Āmantu billāh?" },
      { type: "num", text: "Was bedeutet Ve rusulihī?" },
      { type: "num", text: "Rezitierte Sure Al-Ikhlas!" },
      { type: "num", text: "Welche sind die bekanntesten Engel?" },
      { type: "num", text: "Wie heißt der Engel, der die göttlichen Offenbarungen überbrachte?" },
      { type: "num", text: "Was ist die Aufgabe der Engel Kiramen Katibin?" },
      { type: "num", text: "Nenne die vier großen Offenbarungsbücher!" },
      { type: "num", text: "Welches Buch wurde dem Propheten Isa (Jesus) offenbart?" },
      { type: "num", text: "Was bedeutet 'alejhis-selām (a.s.)?" },
      { type: "num", text: "Welches ist das letzte Buch Allahs?" },
      { type: "num", text: "Wie viele Suren hat der Koran?" },
      { type: "num", text: "Wie viele Propheten werden im Koran namentlich genannt?" },
      { type: "num", text: "Wer war der erste Mensch und der erste Prophet?" },
      { type: "num", text: "Wer ist der letzte Gesandte Allahs?" },
      { type: "num", text: "Wann wurde der Prophet Muhammed (a.s.) geboren?" },
      { type: "num", text: "In welchem Lebensjahr erhielt der Prophet die erste Offenbarung?" },
      { type: "num", text: "Rezitierte das Gedicht / Nasheed über den Propheten!" },
      { type: "num", text: "Wann wird der Jüngste Tag eintreffen?" },
      { type: "num", text: "Was ist der Lohn für die Gläubigen im Jenseits?" },
      { type: "num", text: "Rezitierte Sure Al-Kawthar!" },
      { type: "num", text: "Wer bestimmt das Schicksal und die Schöpfung?" },
    ],
  },

  // ── TOPIC 3 ──
  {
    topic_key: "topic_3",
    bosnianTitle: "Islamski šarti i Sura Felek",
    germanTitle: "Die Säulen des Islam & Sure Al-Falaq",
    sortOrder: 23,
    blocks: [
      { type: "h", level: 2, text: "Die Säulen des Islam (Die fünf Hauptpflichten)" },
      { type: "p", text: "Die Säulen des Islam sind die grundlegenden praktischen Pflichten jedes Muslims. Sie sind im Koran vorgeschrieben. Neben dem Glauben im Herzen ist jeder Gläubige verpflichtet, diese Taten zu verrichten." },
      { type: "h", level: 3, text: "Es gibt fünf Hauptpflichten im Islam:" },
      { type: "num", text: "KELIME-I-ŠEHADET (Das Glaubensbekenntnis sprechen)" },
      { type: "num", text: "NAMAZE KLANJATI (Die fünf täglichen Gebete verrichten)" },
      { type: "num", text: "RAMAZAN POSTITI (Im Monat Ramadan fasten)" },
      { type: "num", text: "ZEKAT DAVATI (Die Armenabgabe entrichten)" },
      { type: "num", text: "HADŽ OBAVITI (Die Pilgerfahrt nach Mekka vollziehen)" },
      { type: "p", text: "Wer diese Pflichten gewissenhaft erfüllt, darf auf Allahs reiche Belohnung und Barmherzigkeit hoffen." },
      { type: "h", level: 2, text: "Sure Al-Falaq (Das Frühlicht)" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "KUL E'ŪZU BI RABBIL-FELEK,\nMIN ŠERRI MĀ HALEK,\nVE MIN ŠERRI GĀSIKIN IZĀ VEKAB,\nVE MIN ŠERRIN-NEFFĀSĀTI FIL-'UKAD,\nVE MIN ŠERRI HĀSIDIN IZĀ HASED." },
      { type: "h", level: 3, text: "Übersetzung:" },
      { type: "p", text: "Sprich: „Ich nehme Zuflucht beim Herrn des Frühlichts\nvor dem Übel dessen, was Er erschaffen hat,\nund vor dem Übel der Dunkelheit, wenn sie hereinbricht,\nund vor dem Übel der Zauberer, die in Knoten blasen,\nund vor dem Übel des Neiders, wenn er neidet!”" },
    ],
  },
  {
    topic_key: "topic_3",
    bosnianTitle: "Prvi islamski šart: Kelime-i-šehadet i Sura Nas",
    germanTitle: "Die 1. Säule des Islam: Shahada & Sure An-Nas",
    sortOrder: 24,
    blocks: [
      { type: "h", level: 2, text: "Die erste Säule des Islam" },
      { type: "h", level: 3, text: "KELIME-I-ŠEHADET — DAS GLAUBENSBEKENNTNIS" },
      { type: "p", text: "Shahada bedeutet: mit dem Herzen fest zu glauben und mit der Zunge zu bezeugen, dass es nur einen einzigen Gott gibt und dass Muhammad Sein Diener und Gesandter ist." },
      { type: "h", level: 3, text: "Wiederholen wir das Glaubensbekenntnis:" },
      { type: "h", level: 3, text: "EŠHEDU EN LĀ ILĀHE ILLALLĀH, VE EŠHEDU ENNE MUHAMMEDEN 'ABDUHŪ VE RESŪLUHŪ." },
      { type: "p", text: "Übersetzung: „Ich bezeuge, dass es keine Gottheit gibt außer Allah, und ich bezeuge, dass Muhammad Allahs Diener und Gesandter ist!”" },
      { type: "p", text: "Mit der Shahada treten wir bewusst in den Islam ein und bekräftigen unsere Hingabe an Allah und die Befolgung Seines Gesandten." },
      { type: "h", level: 2, text: "Sure An-Nas (Die Menschen)" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "KUL E'ŪZU BI RABBIN-NĀS,\nMELIKIN-NĀS,\nILĀHIN-NĀS,\nMIN ŠERRIL-VESVĀSIL-HANNĀS,\nELLEZĪ JUVESVISU FĪ SUDŪRIN-NĀS,\nMINEL-DŽINNETI VEN-NĀS." },
      { type: "h", level: 3, text: "Übersetzung:" },
      { type: "p", text: "Sprich: „Ich nehme Zuflucht beim Herrn der Menschen,\ndem Herrscher der Menschen,\ndem Gott der Menschen,\nvor dem Übel des einflüsternden Schaytans,\nder böse Gedanken in die Herzen der Menschen einflüstert –\nvon den Dschinn und den Menschen!”" },
    ],
  },
  {
    topic_key: "topic_3",
    bosnianTitle: "Drugi islamski šart: Propisane namaze klanjati",
    germanTitle: "Die 2. Säule des Islam: Das Gebet (Salah)",
    sortOrder: 25,
    blocks: [
      { type: "h", level: 2, text: "Die zweite Säule des Islam" },
      { type: "h", level: 3, text: "DIE VORGESCHRIEBENEN GEBETE VERRICHTEN" },
      { type: "p", text: "Das Gebet ist eine grundlegende Pflicht im Islam, die im Koran geboten und durch die Praxis des Propheten vorgelebt wurde. Durch das Gebet erweisen wir Allah demütige Dankbarkeit und Anbetung." },
      { type: "img", url: "/lessons/prayers/00_daily_prayers.jpg", caption: "Die fünf täglichen Pflichtgebete im Tagesverlauf: Fadschr, Dhuhr, Asr, Maghrib und Ischa" },
      { type: "h", level: 3, text: "Im Laufe eines Tages verrichten wir fünf Pflichtgebete:" },
      { type: "b", text: "SABAH (FADSCHR): Vor Sonnenaufgang." },
      { type: "b", text: "PODNE (DHUHR): Am Mittag, wenn die Sonne ihren Höchststand überschritten hat." },
      { type: "b", text: "IKINDIJA (ASR): Am Nachmittag." },
      { type: "b", text: "AKŠAM (MAGHRIB): Direkt nach Sonnenuntergang." },
      { type: "b", text: "JACIJA (ISHA): Bei vollkommener Nacht." },
      { type: "h", level: 3, text: "Weitere wichtige Gebete:" },
      { type: "b", text: "DŽUMA (FREITAGSGEBET): Wird freitags zur Mittagszeit in der Moschee verrichtet." },
      { type: "b", text: "TERAVIJA (TARAWEEH): Wird während des Monats Ramadan nach dem Ischa-Gebet verrichtet." },
      { type: "b", text: "BAJRAM (FESTTAGSGEBET): Wird am ersten Tag des Festes zweimal im Jahr verrichtet." },
      { type: "b", text: "DŽENAZA (TOTENGEBET): Wird für verstorbene Muslime verrichtet." },
      { type: "h", level: 3, text: "Die wichtigsten Gebetshaltungen (Gebetssäulen):" },
      { type: "img", url: "/lessons/prayers/01_takbir.jpg", caption: "1. Takbir (Eröffnungstakbir): Hände auf Ohrhöhe erheben und »Allāhu Akbar« sprechen" },
      { type: "p", text: "1. Takbir (Iftitāh at-Takbīr): Das Gebet beginnt mit dem Heben der Hände auf Ohrhöhe und dem Sprechen von »Allāhu Akbar« (Allah ist der Größte)." },
      { type: "img", url: "/lessons/prayers/02_qiyam.jpg", caption: "2. Qiyam: Aufrechtes Stehen mit gefalteten Händen" },
      { type: "p", text: "2. Qiyam: Ruhiges, ehrfürchtiges Stehen auf dem Gebetsteppich mit Blick zum Gebetsplatz. Die rechte Hand liegt über dem linken Handgelenk auf Brust oder Bauch." },
      { type: "img", url: "/lessons/prayers/03_ruku.jpg", caption: "3. Ruku': Verbeugung mit geradem Rücken und Händen auf den Knien" },
      { type: "p", text: "3. Ruku': Verbeugung nach vorne mit geradem Rücken, Hände umfassen die Knie, dreimal »Subhāna Rabbiyal-'Azīm« sprechen." },
      { type: "img", url: "/lessons/prayers/04_itidal.jpg", caption: "4. I'tidal: Aufrichten aus der Verbeugung" },
      { type: "p", text: "4. I'tidal: Wieder aufrecht stehen und dabei »Sami' Allāhu liman hamidah« und »Rabbanā lakal-hamd« sprechen." },
      { type: "img", url: "/lessons/prayers/05_sajdah.jpg", caption: "5. Sajdah: Niederwerfung vor Allah auf Stirn, Nase, Handflächen, Knie und Zehen" },
      { type: "p", text: "5. Sajdah (Sedschda): Vollständige Niederwerfung auf dem Teppich in tiefer Demut vor Allah, dreimal »Subhāna Rabbiyal-A'lā« sprechen. Zwei Niederwerfungen pro Gebetsabschnitt (Raka'ah)." },
      { type: "img", url: "/lessons/prayers/06_tashahhud.jpg", caption: "6. Qa'da Akhira: Sitzen und Bezeugung des Glaubens (Tashahhud)" },
      { type: "p", text: "6. Qa'da Akhira: Ruhiges Sitzen auf den Beinen, Rezitation des At-Tahiyyat, Segenswünsche auf den Propheten (Salawat) und Bittgebete, mit erhobenem Zeigefinger beim Glaubensbekenntnis." },
      { type: "p", text: "Kinder lernen das Beten mit Beginn des Schulalters und sind ab dem 10. Lebensjahr zum regelmäßigen Gebet angehalten." },
    ],
  },
  {
    topic_key: "topic_3",
    bosnianTitle: "Treći islamski šart: Postiti mjesec ramazan",
    germanTitle: "Die 3. Säule des Islam: Das Fasten im Ramadan (Sawm)",
    sortOrder: 26,
    blocks: [
      { type: "h", level: 2, text: "Die dritte Säule des Islam" },
      { type: "h", level: 3, text: "IM MONAT RAMADAN FASTEN" },
      { type: "p", text: "Das Fasten ist eine koranische Pflicht. Ramadan-Fasten bedeutet, sich von der Morgendämmerung bis zum Sonnenuntergang des Essens, Trinkens und aller schlechten Taten und Worte zu enthalten." },
      { type: "p", text: "Ramadan ist der heiligste Monat des Jahres, in dem die Herabsendung des Korans begann. Wir fasten, spenden Zakat und Sadekatul-Fitr, beten Taraweeh, laden zu gemeinsamen Iftaren ein und lesen den Koran." },
      { type: "h", level: 3, text: "Die Absicht (Nijet) für das Fasten:" },
      { type: "h", level: 3, text: "NEVEJTU EN ESŪME GADEN LILLĀHI TE'ĀLA FERĪDATEN MIN ŠEHRI RAMADĀNE." },
      { type: "p", text: "Bedeutung: „Ich beabsichtige, um Allahs willen am morgigen Tag des Monats Ramadan die Fastenpflicht zu erfüllen!”" },
      { type: "h", level: 3, text: "Das Bittgebet zum Fastenbrechen (Iftar):" },
      { type: "h", level: 3, text: "ALLĀHUMME INNĪ LEKE SUMTU, VE BIKE ĀMENTU, VE 'ALEJKE TEVEKKELTU VE 'ALĀ RIZKIKE EFTARTU." },
      { type: "p", text: "Bedeutung: „O mein Allah, für Dich habe ich gefastet, an Dich glaube ich, auf Dich vertraue ich und mit Deiner Versorgung breche ich mein Fasten!”" },
      { type: "p", text: "Zum Fasten sind alle erwachsenen, gesunden und zurechnungsfähigen Muslime verpflichtet. Der Ramadan endet mit dem freudigen Ramadan-Fest (Ramazanski bajram)." },
    ],
  },
  {
    topic_key: "topic_3",
    bosnianTitle: "Četvrti islamski šart: Zekat davati i Sura Leheb",
    germanTitle: "Die 4. Säule des Islam: Zakat geben & Sure Al-Lahab",
    sortOrder: 27,
    blocks: [
      { type: "h", level: 2, text: "Die vierte Säule des Islam" },
      { type: "h", level: 3, text: "DIE ZAKAT-PFLICHTABGABE ENTRICHTEN" },
      { type: "p", text: "Die Zakat ist eine im Koran vorgeschriebene Pflichtabgabe für vermögende Muslime, einen festgelegten Teil ihres überschüssigen Vermögens an Bedürftige und Bildungseinrichtungen zu spenden." },
      { type: "p", text: "Die Zakat reinigt das Vermögen, schützt das Herz vor Geiz und stärkt die soziale Solidarität in der Gemeinschaft. Zakat wird meist im Ramadan entrichtet, kann aber das ganze Jahr über gegeben werden." },
      { type: "h", level: 3, text: "Vermögenswerte, auf die Zakat anfällt:" },
      { type: "b", text: "Ernte- und Landwirtschaftserzeugnisse" },
      { type: "b", text: "Gold, Silber und Geldvermögen" },
      { type: "b", text: "Handelswaren" },
      { type: "b", text: "Viehbestände" },
      { type: "p", text: "Die Organisation und Verteilung der Zakat obliegt der islamischen Gemeinschaft." },
      { type: "h", level: 2, text: "Sure Al-Lahab (Die Flammen)" },
      { type: "h", level: 3, text: "BISMILLĀHIR-RAHMĀNIR-RAHĪM" },
      { type: "p", text: "TEBBET JEDĀ EBĪ LEHEBIN VE TEBB,\nMĀ AGNĀ 'ANHU MĀLUHŪ VE MĀ KESEB,\nSE JASLĀ NĀREN ZĀTE LEHEB,\nVEMRE-'ETUHŪ HAMMĀLETEL-HATAB,\nFĪ DŽĪDIHĀ HABLUN MIN MESED." },
      { type: "h", level: 3, text: "Übersetzung:" },
      { type: "p", text: "Zugrunde gehen sollen die Hände Abu Lahabs, und zugrunde gegangen ist er!\nNicht nützen wird ihm sein Vermögen und was er erworben hat.\nEr wird in einem lodernden Feuer brennen,\nund auch seine Frau, die Holzträgerin (die Zwietracht sät);\num ihren Hals ein Strick aus Palmfasern!" },
    ],
  },
  {
    topic_key: "topic_3",
    bosnianTitle: "Peti islamski šart: Hadž obaviti i Telbija",
    germanTitle: "Die 5. Säule des Islam: Die Pilgerfahrt (Hadsch) & Talbiya",
    sortOrder: 28,
    blocks: [
      { type: "h", level: 2, text: "Die fünfte Säule des Islam" },
      { type: "h", level: 3, text: "DIE PILGERFAHRT (HADSCH) VOLLZIEHEN" },
      { type: "p", text: "Der Hadsch ist die fünfte Säule des Islam und ein göttliches Gebot für jeden volljährigen, gesunden und finanziell fähigen Muslim, ihn einmal im Leben zu vollziehen. Der Hadsch ist der Besuch der Kaaba und der heiligen Stätten in Mekka." },
      { type: "p", text: "Vor der Abreise begleicht der Pilger alle Schulden und sichert den Unterhalt seiner Familie ab." },
      { type: "h", level: 3, text: "Das Talbiya-Gebet des Pilgers:" },
      { type: "p", text: "Lebbejkellāhumme, lebbejk,\nlebbejkallāhu!\nlebbejkellāhumme, lebbejk,\nlebbejkellāh!\n\nHier bin ich, o Allah, zu Deinem Dienst bereit! Du hast keinen Teilhaber, hier bin ich! Alles Lob, alle Gnade und alle Herrschaft gehören Dir! Du hast keinen Teilhaber!" },
      { type: "h", level: 3, text: "Gedicht: An der Kaaba stand ich" },
      { type: "p", text: "An der Kaaba stand ich still,\nerfüllte, was mein Schöpfer will,\nmeine Sünden wusch ich rein,\nwollte nah bei Allah sein!\n\nIch rief zu meinem Herrn:\nLebbejkellāhumme lebbejk!\n\nIm Tawaf zog ich umher,\nwie ein Stern im Himmelsmeer,\nvoller Ehrfurcht und Gebet,\ndas zum Himmel aufwärts weht.\n\nBeim Brunnen Zamzam rein und klar,\nwo die Hoffnung lebendig war,\nfließt der Glaube voller Kraft,\nder uns ew'ges Leben schafft." },
    ],
  },
  {
    topic_key: "topic_3",
    bosnianTitle: "Ponavljanje gradiva — Islamski šarti",
    germanTitle: "Wiederholung — Die Säulen des Islam",
    sortOrder: 29,
    blocks: [
      { type: "h", level: 2, text: "Wiederholung ist die Mutter des Wissens" },
      { type: "p", text: "Überprüfe dein Wissen über die Pflichten im Islam:" },
      { type: "num", text: "Wie viele Hauptpflichten (Säulen) gibt es im Islam?" },
      { type: "num", text: "Wie lautet die erste Säule des Islam?" },
      { type: "num", text: "Was bezeugen wir mit der Shahada?" },
      { type: "num", text: "Welche ist die zweite Säule des Islam?" },
      { type: "num", text: "Wie viele tägliche Gebete verrichten wir?" },
      { type: "num", text: "Wann verrichten wir das Fadschr-Gebet (Sabah)?" },
      { type: "num", text: "Wann wird das Freitagsgebet (Dschuma) verrichtet?" },
      { type: "num", text: "Wie lautet die dritte Säule des Islam?" },
      { type: "num", text: "Wie lautet die Absicht (Nijet) für das Fasten?" },
      { type: "num", text: "Rezitierte das Bittgebet zum Fastenbrechen (Iftar)!" },
      { type: "num", text: "Wovon enthalten wir uns während des Fastens?" },
      { type: "num", text: "Wer ist zum Fasten verpflichtet?" },
      { type: "num", text: "Wie lautet die vierte Säule des Islam?" },
      { type: "num", text: "Auf welche Vermögenswerte entrichten wir die Zakat?" },
      { type: "num", text: "Was ist der Hadsch?" },
      { type: "num", text: "Wer ist verpflichtet, den Hadsch zu vollziehen?" },
      { type: "num", text: "Rezitierte Sure Al-Falaq!" },
      { type: "num", text: "Wie lautet Sure An-Nas?" },
      { type: "num", text: "Rezitierte Sure Al-Lahab!" },
    ],
  },
];
